###########################################################################
# Copyright 2022 Broadband Forum
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###########################################################################
version: '3.5'
networks:
  baadist_default:
    driver: bridge
    name: baadist_default

services:
  polt-simulator:
    image: broadbandforum/obbaa-polt-simulator:latest
    stdin_open: true
    tty: true
    container_name: polt-simulator

    command: ["-dummy_tr385", "-d"]
    hostname: polt-simulator

    environment:
      - PASSWD=root
    ports:
      - "10830:10830"

    networks:
      - baadist_default


  onu-simulator:
    image: broadbandforum/obbaa-onu-simulator:latest
    stdin_open: true
    tty: true
    container_name: onu-simulator

    entrypoint: python3
    command: ["/usr/local/bin/onusim.py", "-p", "50000","-n","CT_1","-i", "1", "-l", "2" ]

    hostname: onu-simulator

    environment:
      - PASSWD=root
    ports:
      - "50000:50000"

    networks:
      - baadist_default
