apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: vproxy
  namespace: obbaa
spec:
  selector:
    matchLabels:
      app: vproxy
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: vproxy
    spec:
      volumes:
        - name: vomci-vproxy-volume
          persistentVolumeClaim:
            claimName: vomci-vproxy-pvclaim
      containers:
        - name: vproxy
          image: broadbandforum/obbaa-vproxy:latest
          env:
            - name: LOCAL_GRPC_SERVER_PORT
              value: "8433"
            - name: REMOTE_GRPC_SERVER_PORT
              value: "58433"
            - name: REMOTE_GRPC_SERVER_ADDR
              value: "vomci-grpc"
            - name: GRPC_SERVER_NAME
              value: "proxy-grpc-2"
            - name: GRPC_CLIENT_NAME
              value: "proxy-grpc-1"
            - name: KAFKA_BOOTSTRAP_SERVER #Kafka bootstrap server, please provide only one address
              value: "kafka:9092"
              # List of Consumer topics, seperated by spaces
            - name: KAFKA_REQUEST_TOPICS
              value: "vomci-proxy-request"
            - name: KAFKA_RESPONSE_TOPICS
              value: "vomci-proxy-response"
            - name: KAFKA_NOTIFICATION_TOPICS
              value: "vomci-proxy-notification"
            - name: VOMCI_KAFKA_SENDER_NAME
              value: "bbf-vproxy"
            - name: VOMCI_KAFKA_VOLTMF_NAME
              value: "vOLTMF"
            - name: BBF_OBBAA_VNF_NAME
              value: "BBF-VPROXY"
            - name: BBF_OBBAA_VNF_TYPE
              value: "VPROXY"
            - name: BBF_OBBAA_VNF_VERSION
              value: "1.0.0"
            - name: BBF_OBBAA_VNF_VENDOR
              value: "BBF"
            - name: BBF_OBBAA_VNF_INSTANCE_NAME
              value: "BBF-vproxy-instance1"
            - name: BBF_OBBBA_VNF_ADMIN_STATE
              value: "unlocked"
          ports:
            - containerPort: 8433
              name: port8433
          volumeMounts:
            - name: vomci-vproxy-volume
              mountPath: /db
      restartPolicy: Always
