apiVersion: v1
kind: Service
metadata:
  name: vproxy
  namespace: obbaa
spec:
  selector:
    app: vproxy
  ports:
    - protocol: TCP
      port: 8433
      targetPort: 8433
      nodePort: 32433  #external port
  type: NodePort