// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tr451_vomci_nbi_service.proto

package org.broadband_forum.obbaa.onu.message.gpb.service;

public final class Tr451VomciNbiService {
  private Tr451VomciNbiService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035tr451_vomci_nbi_service.proto\022\032tr451_v" +
      "omci_nbi_service.v1\032\035tr451_vomci_nbi_mes" +
      "sage.proto\032\033google/protobuf/empty.proto2" +
      "\230\005\n\017VomciMessageNbi\022I\n\005Hello\022\037.tr451_vom" +
      "ci_nbi_message.v1.Msg\032\037.tr451_vomci_nbi_" +
      "message.v1.Msg\022K\n\007GetData\022\037.tr451_vomci_" +
      "nbi_message.v1.Msg\032\037.tr451_vomci_nbi_mes" +
      "sage.v1.Msg\022Q\n\rReplaceConfig\022\037.tr451_vom" +
      "ci_nbi_message.v1.Msg\032\037.tr451_vomci_nbi_" +
      "message.v1.Msg\022W\n\023UpdateConfigReplica\022\037." +
      "tr451_vomci_nbi_message.v1.Msg\032\037.tr451_v" +
      "omci_nbi_message.v1.Msg\022X\n\024UpdateConfigI" +
      "nstance\022\037.tr451_vomci_nbi_message.v1.Msg" +
      "\032\037.tr451_vomci_nbi_message.v1.Msg\022G\n\003RPC" +
      "\022\037.tr451_vomci_nbi_message.v1.Msg\032\037.tr45" +
      "1_vomci_nbi_message.v1.Msg\022J\n\006Action\022\037.t" +
      "r451_vomci_nbi_message.v1.Msg\032\037.tr451_vo" +
      "mci_nbi_message.v1.Msg\022R\n\025ListenForNotif" +
      "ication\022\026.google.protobuf.Empty\032\037.tr451_" +
      "vomci_nbi_message.v1.Msg0\001B5\n1org.broadb" +
      "and_forum.obbaa.onu.message.gpb.serviceP" +
      "\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.broadband_forum.obbaa.onu.message.gpb.message.Tr451VomciNbiMessage.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    org.broadband_forum.obbaa.onu.message.gpb.message.Tr451VomciNbiMessage.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
