###########################################################################
# Copyright 2023 Broadband Forum
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###########################################################################
version: '3.5'
networks:
    onu_pm_default:
        driver: bridge
        name: onu_pm_default
services:
    onu-pm-collector:
        image: onu-pm-collector
        container_name: onu-pm-collector
        restart: always
        ports:
            - "9005:5005"
            - "4495:4495"
        environment:
            - ONU_PM_COLLECTOR_PORT=4495
            - IONU_PM_COLLECTOR_MAX_CONNECTION=10000
            - DEBUG=true
            - INFLUXDB_ORGANISATION=broadband_forum
            - INFLUXDB_BUCKETID=onu-pm-collection
            - INFLUXDB_API_URL=http://obbaa-influxdb:9999
            - INFLUXDB_TOKEN=_6Mb0Td0U5pbKecnJZ0ajSSw3uGJZggVpLmr9WDdAbXsTDImNZI3pO3zj5OgJtoiGXV6-1HGD5E8xi_4GwFw-g==
            - PMD_MAX_BUFFERED_POINTS=5000
            - PMD_MAX_BUFFERED_MEASUREMENTS=100
            - PMD_TIMEOUT_BUFFERED_POINTS=60
            - PMD_NBI_PORT=5051
            - KAFKA_TELEMETRY_TOPICS=vomci1-telemetry
        networks:
            - onu_pm_default
        tty: true
        stdin_open: true
