apiVersion: v1
kind: Service
metadata:
  name: vomci
  namespace: obbaa
spec:
  selector:
    app: vomci
  ports:
    - name: port8081
      protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 32081  #external port
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: vomci-grpc
  namespace: obbaa
spec:
  selector:
    app: vomci
  ports:
    - protocol: TCP
      port: 58433
      targetPort: 58433
  type: ClusterIP