apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Chart.Name }}
  namespace: obbaa
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  replicas: {{ default 1 .Values.replicaCount | int }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      restartPolicy: Always
      containers:
      - name: {{ .Chart.Name }}
        image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        resources: {{ .Values.resources | toYaml | nindent 12 }}
        env:
          - name: VNF_NAME
            value: {{ .Chart.Name | quote }}
          - name: KAFKA_HOST
            value: {{ .Values.env.kafkaHost | quote }}
          - name: KAFKA_PORT
            value: {{ .Values.env.kafkaPort | quote }}
          - name: MONGO_HOST
            value: {{ .Values.env.mongoHost | quote }}
          - name: MONGO_PORT
            value: {{ .Values.env.mongoPort | quote }}
          - name: DB_NAME
            value: {{ .Values.env.dbName | quote }}
          - name: SOCKET_GRPC
            value: {{printf "%s:%s" .Values.env.socketGrpcAddress .Values.env.socketGrpcPort | quote }}
          - name: DISCARD_ON_ERROR
            value: {{ .Values.env.discardOnError | quote }}
          - name: VNF_MODE
            value: {{ .Values.env.vnfMode | quote }}
        ports:
          - containerPort: {{ .Values.containerPort.number | int }}
            name: {{ .Values.containerPort.name }}
        command: {{ .Values.command | toYaml | nindent 12 }} 