apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: obbaa
spec:
  type: NodePort
  selector:
    app: {{ .Chart.Name }}
  ports:
  - port: 50051
    targetPort: 50051
    nodePort: {{ .Values.service.nodePort }}
    protocol: TCP
