apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: obbaa
spec:
  selector:
    app: zookeeper
  ports:
    - name: port2181
      protocol: TCP
      port: 2181
      targetPort: 2181
    - name: port2888
      protocol: TCP
      port: 2888
      targetPort: 2888
    - name: port3888
      protocol: TCP
      port: 3888
      targetPort: 3888
  type: ClusterIP
