apiVersion: v1
kind: Service
metadata:
  name: microservices-discovery
  namespace: obbaa
spec:
  selector:
    app: microservices-discovery
  ports:
    - name: port8093
      protocol: TCP
      port: 8093
      targetPort: 8093
  type: ClusterIP