// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tr451_vomci_nbi_message.proto

package org.broadband_forum.obbaa.onu.message.gpb.message;

public interface BodyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tr451_vomci_nbi_message.v1.Body)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.tr451_vomci_nbi_message.v1.Request request = 1;</code>
   * @return Whether the request field is set.
   */
  boolean hasRequest();
  /**
   * <code>.tr451_vomci_nbi_message.v1.Request request = 1;</code>
   * @return The request.
   */
  org.broadband_forum.obbaa.onu.message.gpb.message.Request getRequest();
  /**
   * <code>.tr451_vomci_nbi_message.v1.Request request = 1;</code>
   */
  org.broadband_forum.obbaa.onu.message.gpb.message.RequestOrBuilder getRequestOrBuilder();

  /**
   * <code>.tr451_vomci_nbi_message.v1.Response response = 2;</code>
   * @return Whether the response field is set.
   */
  boolean hasResponse();
  /**
   * <code>.tr451_vomci_nbi_message.v1.Response response = 2;</code>
   * @return The response.
   */
  org.broadband_forum.obbaa.onu.message.gpb.message.Response getResponse();
  /**
   * <code>.tr451_vomci_nbi_message.v1.Response response = 2;</code>
   */
  org.broadband_forum.obbaa.onu.message.gpb.message.ResponseOrBuilder getResponseOrBuilder();

  /**
   * <code>.tr451_vomci_nbi_message.v1.Notification notification = 3;</code>
   * @return Whether the notification field is set.
   */
  boolean hasNotification();
  /**
   * <code>.tr451_vomci_nbi_message.v1.Notification notification = 3;</code>
   * @return The notification.
   */
  org.broadband_forum.obbaa.onu.message.gpb.message.Notification getNotification();
  /**
   * <code>.tr451_vomci_nbi_message.v1.Notification notification = 3;</code>
   */
  org.broadband_forum.obbaa.onu.message.gpb.message.NotificationOrBuilder getNotificationOrBuilder();

  public org.broadband_forum.obbaa.onu.message.gpb.message.Body.MsgBodyCase getMsgBodyCase();
}
