// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tr451_vomci_nbi_message.proto

package org.broadband_forum.obbaa.onu.message.gpb.message;

public interface HeaderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tr451_vomci_nbi_message.v1.Header)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Message identifier to
   * </pre>
   *
   * <code>string msg_id = 1;</code>
   * @return The msgId.
   */
  java.lang.String getMsgId();
  /**
   * <pre>
   * Message identifier to
   * </pre>
   *
   * <code>string msg_id = 1;</code>
   * @return The bytes for msgId.
   */
  com.google.protobuf.ByteString
      getMsgIdBytes();

  /**
   * <pre>
   * 1) Identify requests and notifications
   * 2) Correlate requests and response
   * </pre>
   *
   * <code>string sender_name = 2;</code>
   * @return The senderName.
   */
  java.lang.String getSenderName();
  /**
   * <pre>
   * 1) Identify requests and notifications
   * 2) Correlate requests and response
   * </pre>
   *
   * <code>string sender_name = 2;</code>
   * @return The bytes for senderName.
   */
  com.google.protobuf.ByteString
      getSenderNameBytes();

  /**
   * <pre>
   * originated the message
   * </pre>
   *
   * <code>string recipient_name = 3;</code>
   * @return The recipientName.
   */
  java.lang.String getRecipientName();
  /**
   * <pre>
   * originated the message
   * </pre>
   *
   * <code>string recipient_name = 3;</code>
   * @return The bytes for recipientName.
   */
  com.google.protobuf.ByteString
      getRecipientNameBytes();

  /**
   * <pre>
   * receive the request
   * </pre>
   *
   * <code>.tr451_vomci_nbi_message.v1.Header.OBJECT_TYPE object_type = 4;</code>
   * @return The enum numeric value on the wire for objectType.
   */
  int getObjectTypeValue();
  /**
   * <pre>
   * receive the request
   * </pre>
   *
   * <code>.tr451_vomci_nbi_message.v1.Header.OBJECT_TYPE object_type = 4;</code>
   * @return The objectType.
   */
  org.broadband_forum.obbaa.onu.message.gpb.message.Header.OBJECT_TYPE getObjectType();

  /**
   * <pre>
   * resource that is subject of the message
   * </pre>
   *
   * <code>string object_name = 5;</code>
   * @return The objectName.
   */
  java.lang.String getObjectName();
  /**
   * <pre>
   * resource that is subject of the message
   * </pre>
   *
   * <code>string object_name = 5;</code>
   * @return The bytes for objectName.
   */
  com.google.protobuf.ByteString
      getObjectNameBytes();
}
