// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tr451_vomci_nbi_message.proto

package org.broadband_forum.obbaa.onu.message.gpb.message;

public interface HelloRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tr451_vomci_nbi_message.v1.HelloResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *The service endpoint the server
   * </pre>
   *
   * <code>string service_endpoint_name = 1;</code>
   * @return The serviceEndpointName.
   */
  java.lang.String getServiceEndpointName();
  /**
   * <pre>
   *The service endpoint the server
   * </pre>
   *
   * <code>string service_endpoint_name = 1;</code>
   * @return The bytes for serviceEndpointName.
   */
  com.google.protobuf.ByteString
      getServiceEndpointNameBytes();

  /**
   * <pre>
   *used to listen on the session
   * </pre>
   *
   * <code>repeated .tr451_vomci_nbi_message.v1.HelloResp.ServerCapability capabilities = 2;</code>
   * @return A list containing the capabilities.
   */
  java.util.List<org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp.ServerCapability> getCapabilitiesList();
  /**
   * <pre>
   *used to listen on the session
   * </pre>
   *
   * <code>repeated .tr451_vomci_nbi_message.v1.HelloResp.ServerCapability capabilities = 2;</code>
   * @return The count of capabilities.
   */
  int getCapabilitiesCount();
  /**
   * <pre>
   *used to listen on the session
   * </pre>
   *
   * <code>repeated .tr451_vomci_nbi_message.v1.HelloResp.ServerCapability capabilities = 2;</code>
   * @param index The index of the element to return.
   * @return The capabilities at the given index.
   */
  org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp.ServerCapability getCapabilities(int index);
  /**
   * <pre>
   *used to listen on the session
   * </pre>
   *
   * <code>repeated .tr451_vomci_nbi_message.v1.HelloResp.ServerCapability capabilities = 2;</code>
   * @return A list containing the enum numeric values on the wire for capabilities.
   */
  java.util.List<java.lang.Integer>
  getCapabilitiesValueList();
  /**
   * <pre>
   *used to listen on the session
   * </pre>
   *
   * <code>repeated .tr451_vomci_nbi_message.v1.HelloResp.ServerCapability capabilities = 2;</code>
   * @param index The index of the value to return.
   * @return The enum numeric value on the wire of capabilities at the given index.
   */
  int getCapabilitiesValue(int index);
}
