// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tr451_vomci_nbi_message.proto

package org.broadband_forum.obbaa.onu.message.gpb.message;

public interface HelloRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tr451_vomci_nbi_message.v1.HelloResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *The service endpoint the server
   * </pre>
   *
   * <code>string service_endpoint_name = 1;</code>
   * @return The serviceEndpointName.
   */
  java.lang.String getServiceEndpointName();
  /**
   * <pre>
   *The service endpoint the server
   * </pre>
   *
   * <code>string service_endpoint_name = 1;</code>
   * @return The bytes for serviceEndpointName.
   */
  com.google.protobuf.ByteString
      getServiceEndpointNameBytes();

  /**
   * <pre>
   *used to listen on the session
   * </pre>
   *
   * <code>repeated .tr451_vomci_nbi_message.v1.NFInformation network_function_info = 2;</code>
   */
  java.util.List<org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation> 
      getNetworkFunctionInfoList();
  /**
   * <pre>
   *used to listen on the session
   * </pre>
   *
   * <code>repeated .tr451_vomci_nbi_message.v1.NFInformation network_function_info = 2;</code>
   */
  org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation getNetworkFunctionInfo(int index);
  /**
   * <pre>
   *used to listen on the session
   * </pre>
   *
   * <code>repeated .tr451_vomci_nbi_message.v1.NFInformation network_function_info = 2;</code>
   */
  int getNetworkFunctionInfoCount();
  /**
   * <pre>
   *used to listen on the session
   * </pre>
   *
   * <code>repeated .tr451_vomci_nbi_message.v1.NFInformation network_function_info = 2;</code>
   */
  java.util.List<? extends org.broadband_forum.obbaa.onu.message.gpb.message.NFInformationOrBuilder> 
      getNetworkFunctionInfoOrBuilderList();
  /**
   * <pre>
   *used to listen on the session
   * </pre>
   *
   * <code>repeated .tr451_vomci_nbi_message.v1.NFInformation network_function_info = 2;</code>
   */
  org.broadband_forum.obbaa.onu.message.gpb.message.NFInformationOrBuilder getNetworkFunctionInfoOrBuilder(
      int index);
}
