// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tr451_vomci_nbi_message.proto

package org.broadband_forum.obbaa.onu.message.gpb.message;

/**
 * Protobuf type {@code tr451_vomci_nbi_message.v1.HelloResp}
 */
public final class HelloResp extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tr451_vomci_nbi_message.v1.HelloResp)
    HelloRespOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HelloResp.newBuilder() to construct.
  private HelloResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HelloResp() {
    serviceEndpointName_ = "";
    capabilities_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new HelloResp();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private HelloResp(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            serviceEndpointName_ = s;
            break;
          }
          case 16: {
            int rawValue = input.readEnum();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              capabilities_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000001;
            }
            capabilities_.add(rawValue);
            break;
          }
          case 18: {
            int length = input.readRawVarint32();
            int oldLimit = input.pushLimit(length);
            while(input.getBytesUntilLimit() > 0) {
              int rawValue = input.readEnum();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                capabilities_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              capabilities_.add(rawValue);
            }
            input.popLimit(oldLimit);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        capabilities_ = java.util.Collections.unmodifiableList(capabilities_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.broadband_forum.obbaa.onu.message.gpb.message.Tr451VomciNbiMessage.internal_static_tr451_vomci_nbi_message_v1_HelloResp_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.broadband_forum.obbaa.onu.message.gpb.message.Tr451VomciNbiMessage.internal_static_tr451_vomci_nbi_message_v1_HelloResp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp.class, org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp.Builder.class);
  }

  /**
   * <pre>
   * supported by the
   * server
   * </pre>
   *
   * Protobuf enum {@code tr451_vomci_nbi_message.v1.HelloResp.ServerCapability}
   */
  public enum ServerCapability
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NO_CAPABILITY_REPORTED = 0;</code>
     */
    NO_CAPABILITY_REPORTED(0),
    /**
     * <code>ONU_STATE_ONLY_SUPPORT = 1;</code>
     */
    ONU_STATE_ONLY_SUPPORT(1),
    /**
     * <code>ONU_CONFIG_REPLICA_SUPPORT = 2;</code>
     */
    ONU_CONFIG_REPLICA_SUPPORT(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>NO_CAPABILITY_REPORTED = 0;</code>
     */
    public static final int NO_CAPABILITY_REPORTED_VALUE = 0;
    /**
     * <code>ONU_STATE_ONLY_SUPPORT = 1;</code>
     */
    public static final int ONU_STATE_ONLY_SUPPORT_VALUE = 1;
    /**
     * <code>ONU_CONFIG_REPLICA_SUPPORT = 2;</code>
     */
    public static final int ONU_CONFIG_REPLICA_SUPPORT_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ServerCapability valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ServerCapability forNumber(int value) {
      switch (value) {
        case 0: return NO_CAPABILITY_REPORTED;
        case 1: return ONU_STATE_ONLY_SUPPORT;
        case 2: return ONU_CONFIG_REPLICA_SUPPORT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ServerCapability>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ServerCapability> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ServerCapability>() {
            public ServerCapability findValueByNumber(int number) {
              return ServerCapability.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp.getDescriptor().getEnumTypes().get(0);
    }

    private static final ServerCapability[] VALUES = values();

    public static ServerCapability valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ServerCapability(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:tr451_vomci_nbi_message.v1.HelloResp.ServerCapability)
  }

  public static final int SERVICE_ENDPOINT_NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object serviceEndpointName_;
  /**
   * <pre>
   *The service endpoint the server
   * </pre>
   *
   * <code>string service_endpoint_name = 1;</code>
   * @return The serviceEndpointName.
   */
  @java.lang.Override
  public java.lang.String getServiceEndpointName() {
    java.lang.Object ref = serviceEndpointName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      serviceEndpointName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *The service endpoint the server
   * </pre>
   *
   * <code>string service_endpoint_name = 1;</code>
   * @return The bytes for serviceEndpointName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getServiceEndpointNameBytes() {
    java.lang.Object ref = serviceEndpointName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      serviceEndpointName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CAPABILITIES_FIELD_NUMBER = 2;
  private java.util.List<java.lang.Integer> capabilities_;
  private static final com.google.protobuf.Internal.ListAdapter.Converter<
      java.lang.Integer, org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp.ServerCapability> capabilities_converter_ =
          new com.google.protobuf.Internal.ListAdapter.Converter<
              java.lang.Integer, org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp.ServerCapability>() {
            public org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp.ServerCapability convert(java.lang.Integer from) {
              @SuppressWarnings("deprecation")
              org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp.ServerCapability result = org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp.ServerCapability.valueOf(from);
              return result == null ? org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp.ServerCapability.UNRECOGNIZED : result;
            }
          };
  /**
   * <pre>
   *used to listen on the session
   * </pre>
   *
   * <code>repeated .tr451_vomci_nbi_message.v1.HelloResp.ServerCapability capabilities = 2;</code>
   * @return A list containing the capabilities.
   */
  @java.lang.Override
  public java.util.List<org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp.ServerCapability> getCapabilitiesList() {
    return new com.google.protobuf.Internal.ListAdapter<
        java.lang.Integer, org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp.ServerCapability>(capabilities_, capabilities_converter_);
  }
  /**
   * <pre>
   *used to listen on the session
   * </pre>
   *
   * <code>repeated .tr451_vomci_nbi_message.v1.HelloResp.ServerCapability capabilities = 2;</code>
   * @return The count of capabilities.
   */
  @java.lang.Override
  public int getCapabilitiesCount() {
    return capabilities_.size();
  }
  /**
   * <pre>
   *used to listen on the session
   * </pre>
   *
   * <code>repeated .tr451_vomci_nbi_message.v1.HelloResp.ServerCapability capabilities = 2;</code>
   * @param index The index of the element to return.
   * @return The capabilities at the given index.
   */
  @java.lang.Override
  public org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp.ServerCapability getCapabilities(int index) {
    return capabilities_converter_.convert(capabilities_.get(index));
  }
  /**
   * <pre>
   *used to listen on the session
   * </pre>
   *
   * <code>repeated .tr451_vomci_nbi_message.v1.HelloResp.ServerCapability capabilities = 2;</code>
   * @return A list containing the enum numeric values on the wire for capabilities.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
  getCapabilitiesValueList() {
    return capabilities_;
  }
  /**
   * <pre>
   *used to listen on the session
   * </pre>
   *
   * <code>repeated .tr451_vomci_nbi_message.v1.HelloResp.ServerCapability capabilities = 2;</code>
   * @param index The index of the value to return.
   * @return The enum numeric value on the wire of capabilities at the given index.
   */
  @java.lang.Override
  public int getCapabilitiesValue(int index) {
    return capabilities_.get(index);
  }
  private int capabilitiesMemoizedSerializedSize;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (!getServiceEndpointNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, serviceEndpointName_);
    }
    if (getCapabilitiesList().size() > 0) {
      output.writeUInt32NoTag(18);
      output.writeUInt32NoTag(capabilitiesMemoizedSerializedSize);
    }
    for (int i = 0; i < capabilities_.size(); i++) {
      output.writeEnumNoTag(capabilities_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getServiceEndpointNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, serviceEndpointName_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < capabilities_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeEnumSizeNoTag(capabilities_.get(i));
      }
      size += dataSize;
      if (!getCapabilitiesList().isEmpty()) {  size += 1;
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32SizeNoTag(dataSize);
      }capabilitiesMemoizedSerializedSize = dataSize;
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp)) {
      return super.equals(obj);
    }
    org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp other = (org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp) obj;

    if (!getServiceEndpointName()
        .equals(other.getServiceEndpointName())) return false;
    if (!capabilities_.equals(other.capabilities_)) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SERVICE_ENDPOINT_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getServiceEndpointName().hashCode();
    if (getCapabilitiesCount() > 0) {
      hash = (37 * hash) + CAPABILITIES_FIELD_NUMBER;
      hash = (53 * hash) + capabilities_.hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tr451_vomci_nbi_message.v1.HelloResp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tr451_vomci_nbi_message.v1.HelloResp)
      org.broadband_forum.obbaa.onu.message.gpb.message.HelloRespOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.broadband_forum.obbaa.onu.message.gpb.message.Tr451VomciNbiMessage.internal_static_tr451_vomci_nbi_message_v1_HelloResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.broadband_forum.obbaa.onu.message.gpb.message.Tr451VomciNbiMessage.internal_static_tr451_vomci_nbi_message_v1_HelloResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp.class, org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp.Builder.class);
    }

    // Construct using org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      serviceEndpointName_ = "";

      capabilities_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.broadband_forum.obbaa.onu.message.gpb.message.Tr451VomciNbiMessage.internal_static_tr451_vomci_nbi_message_v1_HelloResp_descriptor;
    }

    @java.lang.Override
    public org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp getDefaultInstanceForType() {
      return org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp.getDefaultInstance();
    }

    @java.lang.Override
    public org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp build() {
      org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp buildPartial() {
      org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp result = new org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp(this);
      int from_bitField0_ = bitField0_;
      result.serviceEndpointName_ = serviceEndpointName_;
      if (((bitField0_ & 0x00000001) != 0)) {
        capabilities_ = java.util.Collections.unmodifiableList(capabilities_);
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.capabilities_ = capabilities_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp) {
        return mergeFrom((org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp other) {
      if (other == org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp.getDefaultInstance()) return this;
      if (!other.getServiceEndpointName().isEmpty()) {
        serviceEndpointName_ = other.serviceEndpointName_;
        onChanged();
      }
      if (!other.capabilities_.isEmpty()) {
        if (capabilities_.isEmpty()) {
          capabilities_ = other.capabilities_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureCapabilitiesIsMutable();
          capabilities_.addAll(other.capabilities_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object serviceEndpointName_ = "";
    /**
     * <pre>
     *The service endpoint the server
     * </pre>
     *
     * <code>string service_endpoint_name = 1;</code>
     * @return The serviceEndpointName.
     */
    public java.lang.String getServiceEndpointName() {
      java.lang.Object ref = serviceEndpointName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serviceEndpointName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *The service endpoint the server
     * </pre>
     *
     * <code>string service_endpoint_name = 1;</code>
     * @return The bytes for serviceEndpointName.
     */
    public com.google.protobuf.ByteString
        getServiceEndpointNameBytes() {
      java.lang.Object ref = serviceEndpointName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serviceEndpointName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *The service endpoint the server
     * </pre>
     *
     * <code>string service_endpoint_name = 1;</code>
     * @param value The serviceEndpointName to set.
     * @return This builder for chaining.
     */
    public Builder setServiceEndpointName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      serviceEndpointName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *The service endpoint the server
     * </pre>
     *
     * <code>string service_endpoint_name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearServiceEndpointName() {
      
      serviceEndpointName_ = getDefaultInstance().getServiceEndpointName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *The service endpoint the server
     * </pre>
     *
     * <code>string service_endpoint_name = 1;</code>
     * @param value The bytes for serviceEndpointName to set.
     * @return This builder for chaining.
     */
    public Builder setServiceEndpointNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      serviceEndpointName_ = value;
      onChanged();
      return this;
    }

    private java.util.List<java.lang.Integer> capabilities_ =
      java.util.Collections.emptyList();
    private void ensureCapabilitiesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        capabilities_ = new java.util.ArrayList<java.lang.Integer>(capabilities_);
        bitField0_ |= 0x00000001;
      }
    }
    /**
     * <pre>
     *used to listen on the session
     * </pre>
     *
     * <code>repeated .tr451_vomci_nbi_message.v1.HelloResp.ServerCapability capabilities = 2;</code>
     * @return A list containing the capabilities.
     */
    public java.util.List<org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp.ServerCapability> getCapabilitiesList() {
      return new com.google.protobuf.Internal.ListAdapter<
          java.lang.Integer, org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp.ServerCapability>(capabilities_, capabilities_converter_);
    }
    /**
     * <pre>
     *used to listen on the session
     * </pre>
     *
     * <code>repeated .tr451_vomci_nbi_message.v1.HelloResp.ServerCapability capabilities = 2;</code>
     * @return The count of capabilities.
     */
    public int getCapabilitiesCount() {
      return capabilities_.size();
    }
    /**
     * <pre>
     *used to listen on the session
     * </pre>
     *
     * <code>repeated .tr451_vomci_nbi_message.v1.HelloResp.ServerCapability capabilities = 2;</code>
     * @param index The index of the element to return.
     * @return The capabilities at the given index.
     */
    public org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp.ServerCapability getCapabilities(int index) {
      return capabilities_converter_.convert(capabilities_.get(index));
    }
    /**
     * <pre>
     *used to listen on the session
     * </pre>
     *
     * <code>repeated .tr451_vomci_nbi_message.v1.HelloResp.ServerCapability capabilities = 2;</code>
     * @param index The index to set the value at.
     * @param value The capabilities to set.
     * @return This builder for chaining.
     */
    public Builder setCapabilities(
        int index, org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp.ServerCapability value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureCapabilitiesIsMutable();
      capabilities_.set(index, value.getNumber());
      onChanged();
      return this;
    }
    /**
     * <pre>
     *used to listen on the session
     * </pre>
     *
     * <code>repeated .tr451_vomci_nbi_message.v1.HelloResp.ServerCapability capabilities = 2;</code>
     * @param value The capabilities to add.
     * @return This builder for chaining.
     */
    public Builder addCapabilities(org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp.ServerCapability value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureCapabilitiesIsMutable();
      capabilities_.add(value.getNumber());
      onChanged();
      return this;
    }
    /**
     * <pre>
     *used to listen on the session
     * </pre>
     *
     * <code>repeated .tr451_vomci_nbi_message.v1.HelloResp.ServerCapability capabilities = 2;</code>
     * @param values The capabilities to add.
     * @return This builder for chaining.
     */
    public Builder addAllCapabilities(
        java.lang.Iterable<? extends org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp.ServerCapability> values) {
      ensureCapabilitiesIsMutable();
      for (org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp.ServerCapability value : values) {
        capabilities_.add(value.getNumber());
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     *used to listen on the session
     * </pre>
     *
     * <code>repeated .tr451_vomci_nbi_message.v1.HelloResp.ServerCapability capabilities = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCapabilities() {
      capabilities_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *used to listen on the session
     * </pre>
     *
     * <code>repeated .tr451_vomci_nbi_message.v1.HelloResp.ServerCapability capabilities = 2;</code>
     * @return A list containing the enum numeric values on the wire for capabilities.
     */
    public java.util.List<java.lang.Integer>
    getCapabilitiesValueList() {
      return java.util.Collections.unmodifiableList(capabilities_);
    }
    /**
     * <pre>
     *used to listen on the session
     * </pre>
     *
     * <code>repeated .tr451_vomci_nbi_message.v1.HelloResp.ServerCapability capabilities = 2;</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of capabilities at the given index.
     */
    public int getCapabilitiesValue(int index) {
      return capabilities_.get(index);
    }
    /**
     * <pre>
     *used to listen on the session
     * </pre>
     *
     * <code>repeated .tr451_vomci_nbi_message.v1.HelloResp.ServerCapability capabilities = 2;</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of capabilities at the given index.
     * @return This builder for chaining.
     */
    public Builder setCapabilitiesValue(
        int index, int value) {
      ensureCapabilitiesIsMutable();
      capabilities_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *used to listen on the session
     * </pre>
     *
     * <code>repeated .tr451_vomci_nbi_message.v1.HelloResp.ServerCapability capabilities = 2;</code>
     * @param value The enum numeric value on the wire for capabilities to add.
     * @return This builder for chaining.
     */
    public Builder addCapabilitiesValue(int value) {
      ensureCapabilitiesIsMutable();
      capabilities_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *used to listen on the session
     * </pre>
     *
     * <code>repeated .tr451_vomci_nbi_message.v1.HelloResp.ServerCapability capabilities = 2;</code>
     * @param values The enum numeric values on the wire for capabilities to add.
     * @return This builder for chaining.
     */
    public Builder addAllCapabilitiesValue(
        java.lang.Iterable<java.lang.Integer> values) {
      ensureCapabilitiesIsMutable();
      for (int value : values) {
        capabilities_.add(value);
      }
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tr451_vomci_nbi_message.v1.HelloResp)
  }

  // @@protoc_insertion_point(class_scope:tr451_vomci_nbi_message.v1.HelloResp)
  private static final org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp();
  }

  public static org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HelloResp>
      PARSER = new com.google.protobuf.AbstractParser<HelloResp>() {
    @java.lang.Override
    public HelloResp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new HelloResp(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<HelloResp> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HelloResp> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.broadband_forum.obbaa.onu.message.gpb.message.HelloResp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

