// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tr451_vomci_nbi_message.proto

package org.broadband_forum.obbaa.onu.message.gpb.message;

/**
 * Protobuf type {@code tr451_vomci_nbi_message.v1.NFInformation}
 */
public  final class NFInformation extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tr451_vomci_nbi_message.v1.NFInformation)
    NFInformationOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NFInformation.newBuilder() to construct.
  private NFInformation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NFInformation() {
    capabilities_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new NFInformation();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private NFInformation(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              nfTypes_ = com.google.protobuf.MapField.newMapField(
                  NfTypesDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            nfTypes__ = input.readMessage(
                NfTypesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            nfTypes_.getMutableMap().put(
                nfTypes__.getKey(), nfTypes__.getValue());
            break;
          }
          case 16: {
            int rawValue = input.readEnum();
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              capabilities_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000002;
            }
            capabilities_.add(rawValue);
            break;
          }
          case 18: {
            int length = input.readRawVarint32();
            int oldLimit = input.pushLimit(length);
            while(input.getBytesUntilLimit() > 0) {
              int rawValue = input.readEnum();
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                capabilities_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              capabilities_.add(rawValue);
            }
            input.popLimit(oldLimit);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        capabilities_ = java.util.Collections.unmodifiableList(capabilities_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.broadband_forum.obbaa.onu.message.gpb.message.Tr451VomciNbiMessage.internal_static_tr451_vomci_nbi_message_v1_NFInformation_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 1:
        return internalGetNfTypes();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.broadband_forum.obbaa.onu.message.gpb.message.Tr451VomciNbiMessage.internal_static_tr451_vomci_nbi_message_v1_NFInformation_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation.class, org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation.Builder.class);
  }

  /**
   * Protobuf enum {@code tr451_vomci_nbi_message.v1.NFInformation.NFCapability}
   */
  public enum NFCapability
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NO_CAPABILITY_REPORTED = 0;</code>
     */
    NO_CAPABILITY_REPORTED(0),
    /**
     * <code>ONU_STATE_ONLY_SUPPORT = 1;</code>
     */
    ONU_STATE_ONLY_SUPPORT(1),
    /**
     * <code>ONU_CONFIG_REPLICA_SUPPORT = 2;</code>
     */
    ONU_CONFIG_REPLICA_SUPPORT(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>NO_CAPABILITY_REPORTED = 0;</code>
     */
    public static final int NO_CAPABILITY_REPORTED_VALUE = 0;
    /**
     * <code>ONU_STATE_ONLY_SUPPORT = 1;</code>
     */
    public static final int ONU_STATE_ONLY_SUPPORT_VALUE = 1;
    /**
     * <code>ONU_CONFIG_REPLICA_SUPPORT = 2;</code>
     */
    public static final int ONU_CONFIG_REPLICA_SUPPORT_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static NFCapability valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static NFCapability forNumber(int value) {
      switch (value) {
        case 0: return NO_CAPABILITY_REPORTED;
        case 1: return ONU_STATE_ONLY_SUPPORT;
        case 2: return ONU_CONFIG_REPLICA_SUPPORT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<NFCapability>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        NFCapability> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<NFCapability>() {
            public NFCapability findValueByNumber(int number) {
              return NFCapability.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation.getDescriptor().getEnumTypes().get(0);
    }

    private static final NFCapability[] VALUES = values();

    public static NFCapability valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private NFCapability(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:tr451_vomci_nbi_message.v1.NFInformation.NFCapability)
  }

  public static final int NF_TYPES_FIELD_NUMBER = 1;
  private static final class NfTypesDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                org.broadband_forum.obbaa.onu.message.gpb.message.Tr451VomciNbiMessage.internal_static_tr451_vomci_nbi_message_v1_NFInformation_NfTypesEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> nfTypes_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetNfTypes() {
    if (nfTypes_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          NfTypesDefaultEntryHolder.defaultEntry);
    }
    return nfTypes_;
  }

  public int getNfTypesCount() {
    return internalGetNfTypes().getMap().size();
  }
  /**
   * <pre>
   *Valid Key types: 
   * </pre>
   *
   * <code>map&lt;string, string&gt; nf_types = 1;</code>
   */

  public boolean containsNfTypes(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetNfTypes().getMap().containsKey(key);
  }
  /**
   * Use {@link #getNfTypesMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getNfTypes() {
    return getNfTypesMap();
  }
  /**
   * <pre>
   *Valid Key types: 
   * </pre>
   *
   * <code>map&lt;string, string&gt; nf_types = 1;</code>
   */

  public java.util.Map<java.lang.String, java.lang.String> getNfTypesMap() {
    return internalGetNfTypes().getMap();
  }
  /**
   * <pre>
   *Valid Key types: 
   * </pre>
   *
   * <code>map&lt;string, string&gt; nf_types = 1;</code>
   */

  public java.lang.String getNfTypesOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetNfTypes().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   *Valid Key types: 
   * </pre>
   *
   * <code>map&lt;string, string&gt; nf_types = 1;</code>
   */

  public java.lang.String getNfTypesOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetNfTypes().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int CAPABILITIES_FIELD_NUMBER = 2;
  private java.util.List<java.lang.Integer> capabilities_;
  private static final com.google.protobuf.Internal.ListAdapter.Converter<
      java.lang.Integer, org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation.NFCapability> capabilities_converter_ =
          new com.google.protobuf.Internal.ListAdapter.Converter<
              java.lang.Integer, org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation.NFCapability>() {
            public org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation.NFCapability convert(java.lang.Integer from) {
              @SuppressWarnings("deprecation")
              org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation.NFCapability result = org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation.NFCapability.valueOf(from);
              return result == null ? org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation.NFCapability.UNRECOGNIZED : result;
            }
          };
  /**
   * <pre>
   * usage-category, vendor-name,
   * software-version
   * </pre>
   *
   * <code>repeated .tr451_vomci_nbi_message.v1.NFInformation.NFCapability capabilities = 2;</code>
   * @return A list containing the capabilities.
   */
  public java.util.List<org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation.NFCapability> getCapabilitiesList() {
    return new com.google.protobuf.Internal.ListAdapter<
        java.lang.Integer, org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation.NFCapability>(capabilities_, capabilities_converter_);
  }
  /**
   * <pre>
   * usage-category, vendor-name,
   * software-version
   * </pre>
   *
   * <code>repeated .tr451_vomci_nbi_message.v1.NFInformation.NFCapability capabilities = 2;</code>
   * @return The count of capabilities.
   */
  public int getCapabilitiesCount() {
    return capabilities_.size();
  }
  /**
   * <pre>
   * usage-category, vendor-name,
   * software-version
   * </pre>
   *
   * <code>repeated .tr451_vomci_nbi_message.v1.NFInformation.NFCapability capabilities = 2;</code>
   * @param index The index of the element to return.
   * @return The capabilities at the given index.
   */
  public org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation.NFCapability getCapabilities(int index) {
    return capabilities_converter_.convert(capabilities_.get(index));
  }
  /**
   * <pre>
   * usage-category, vendor-name,
   * software-version
   * </pre>
   *
   * <code>repeated .tr451_vomci_nbi_message.v1.NFInformation.NFCapability capabilities = 2;</code>
   * @return A list containing the enum numeric values on the wire for capabilities.
   */
  public java.util.List<java.lang.Integer>
  getCapabilitiesValueList() {
    return capabilities_;
  }
  /**
   * <pre>
   * usage-category, vendor-name,
   * software-version
   * </pre>
   *
   * <code>repeated .tr451_vomci_nbi_message.v1.NFInformation.NFCapability capabilities = 2;</code>
   * @param index The index of the value to return.
   * @return The enum numeric value on the wire of capabilities at the given index.
   */
  public int getCapabilitiesValue(int index) {
    return capabilities_.get(index);
  }
  private int capabilitiesMemoizedSerializedSize;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetNfTypes(),
        NfTypesDefaultEntryHolder.defaultEntry,
        1);
    if (getCapabilitiesList().size() > 0) {
      output.writeUInt32NoTag(18);
      output.writeUInt32NoTag(capabilitiesMemoizedSerializedSize);
    }
    for (int i = 0; i < capabilities_.size(); i++) {
      output.writeEnumNoTag(capabilities_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetNfTypes().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      nfTypes__ = NfTypesDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, nfTypes__);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < capabilities_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeEnumSizeNoTag(capabilities_.get(i));
      }
      size += dataSize;
      if (!getCapabilitiesList().isEmpty()) {  size += 1;
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32SizeNoTag(dataSize);
      }capabilitiesMemoizedSerializedSize = dataSize;
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation)) {
      return super.equals(obj);
    }
    org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation other = (org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation) obj;

    if (!internalGetNfTypes().equals(
        other.internalGetNfTypes())) return false;
    if (!capabilities_.equals(other.capabilities_)) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetNfTypes().getMap().isEmpty()) {
      hash = (37 * hash) + NF_TYPES_FIELD_NUMBER;
      hash = (53 * hash) + internalGetNfTypes().hashCode();
    }
    if (getCapabilitiesCount() > 0) {
      hash = (37 * hash) + CAPABILITIES_FIELD_NUMBER;
      hash = (53 * hash) + capabilities_.hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tr451_vomci_nbi_message.v1.NFInformation}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tr451_vomci_nbi_message.v1.NFInformation)
      org.broadband_forum.obbaa.onu.message.gpb.message.NFInformationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.broadband_forum.obbaa.onu.message.gpb.message.Tr451VomciNbiMessage.internal_static_tr451_vomci_nbi_message_v1_NFInformation_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetNfTypes();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableNfTypes();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.broadband_forum.obbaa.onu.message.gpb.message.Tr451VomciNbiMessage.internal_static_tr451_vomci_nbi_message_v1_NFInformation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation.class, org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation.Builder.class);
    }

    // Construct using org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      internalGetMutableNfTypes().clear();
      capabilities_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.broadband_forum.obbaa.onu.message.gpb.message.Tr451VomciNbiMessage.internal_static_tr451_vomci_nbi_message_v1_NFInformation_descriptor;
    }

    @java.lang.Override
    public org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation getDefaultInstanceForType() {
      return org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation.getDefaultInstance();
    }

    @java.lang.Override
    public org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation build() {
      org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation buildPartial() {
      org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation result = new org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation(this);
      int from_bitField0_ = bitField0_;
      result.nfTypes_ = internalGetNfTypes();
      result.nfTypes_.makeImmutable();
      if (((bitField0_ & 0x00000002) != 0)) {
        capabilities_ = java.util.Collections.unmodifiableList(capabilities_);
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.capabilities_ = capabilities_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation) {
        return mergeFrom((org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation other) {
      if (other == org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation.getDefaultInstance()) return this;
      internalGetMutableNfTypes().mergeFrom(
          other.internalGetNfTypes());
      if (!other.capabilities_.isEmpty()) {
        if (capabilities_.isEmpty()) {
          capabilities_ = other.capabilities_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureCapabilitiesIsMutable();
          capabilities_.addAll(other.capabilities_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> nfTypes_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetNfTypes() {
      if (nfTypes_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            NfTypesDefaultEntryHolder.defaultEntry);
      }
      return nfTypes_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableNfTypes() {
      onChanged();;
      if (nfTypes_ == null) {
        nfTypes_ = com.google.protobuf.MapField.newMapField(
            NfTypesDefaultEntryHolder.defaultEntry);
      }
      if (!nfTypes_.isMutable()) {
        nfTypes_ = nfTypes_.copy();
      }
      return nfTypes_;
    }

    public int getNfTypesCount() {
      return internalGetNfTypes().getMap().size();
    }
    /**
     * <pre>
     *Valid Key types: 
     * </pre>
     *
     * <code>map&lt;string, string&gt; nf_types = 1;</code>
     */

    public boolean containsNfTypes(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetNfTypes().getMap().containsKey(key);
    }
    /**
     * Use {@link #getNfTypesMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getNfTypes() {
      return getNfTypesMap();
    }
    /**
     * <pre>
     *Valid Key types: 
     * </pre>
     *
     * <code>map&lt;string, string&gt; nf_types = 1;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getNfTypesMap() {
      return internalGetNfTypes().getMap();
    }
    /**
     * <pre>
     *Valid Key types: 
     * </pre>
     *
     * <code>map&lt;string, string&gt; nf_types = 1;</code>
     */

    public java.lang.String getNfTypesOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetNfTypes().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     *Valid Key types: 
     * </pre>
     *
     * <code>map&lt;string, string&gt; nf_types = 1;</code>
     */

    public java.lang.String getNfTypesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetNfTypes().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearNfTypes() {
      internalGetMutableNfTypes().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     *Valid Key types: 
     * </pre>
     *
     * <code>map&lt;string, string&gt; nf_types = 1;</code>
     */

    public Builder removeNfTypes(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableNfTypes().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableNfTypes() {
      return internalGetMutableNfTypes().getMutableMap();
    }
    /**
     * <pre>
     *Valid Key types: 
     * </pre>
     *
     * <code>map&lt;string, string&gt; nf_types = 1;</code>
     */
    public Builder putNfTypes(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableNfTypes().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <pre>
     *Valid Key types: 
     * </pre>
     *
     * <code>map&lt;string, string&gt; nf_types = 1;</code>
     */

    public Builder putAllNfTypes(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableNfTypes().getMutableMap()
          .putAll(values);
      return this;
    }

    private java.util.List<java.lang.Integer> capabilities_ =
      java.util.Collections.emptyList();
    private void ensureCapabilitiesIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        capabilities_ = new java.util.ArrayList<java.lang.Integer>(capabilities_);
        bitField0_ |= 0x00000002;
      }
    }
    /**
     * <pre>
     * usage-category, vendor-name,
     * software-version
     * </pre>
     *
     * <code>repeated .tr451_vomci_nbi_message.v1.NFInformation.NFCapability capabilities = 2;</code>
     * @return A list containing the capabilities.
     */
    public java.util.List<org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation.NFCapability> getCapabilitiesList() {
      return new com.google.protobuf.Internal.ListAdapter<
          java.lang.Integer, org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation.NFCapability>(capabilities_, capabilities_converter_);
    }
    /**
     * <pre>
     * usage-category, vendor-name,
     * software-version
     * </pre>
     *
     * <code>repeated .tr451_vomci_nbi_message.v1.NFInformation.NFCapability capabilities = 2;</code>
     * @return The count of capabilities.
     */
    public int getCapabilitiesCount() {
      return capabilities_.size();
    }
    /**
     * <pre>
     * usage-category, vendor-name,
     * software-version
     * </pre>
     *
     * <code>repeated .tr451_vomci_nbi_message.v1.NFInformation.NFCapability capabilities = 2;</code>
     * @param index The index of the element to return.
     * @return The capabilities at the given index.
     */
    public org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation.NFCapability getCapabilities(int index) {
      return capabilities_converter_.convert(capabilities_.get(index));
    }
    /**
     * <pre>
     * usage-category, vendor-name,
     * software-version
     * </pre>
     *
     * <code>repeated .tr451_vomci_nbi_message.v1.NFInformation.NFCapability capabilities = 2;</code>
     * @param index The index to set the value at.
     * @param value The capabilities to set.
     * @return This builder for chaining.
     */
    public Builder setCapabilities(
        int index, org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation.NFCapability value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureCapabilitiesIsMutable();
      capabilities_.set(index, value.getNumber());
      onChanged();
      return this;
    }
    /**
     * <pre>
     * usage-category, vendor-name,
     * software-version
     * </pre>
     *
     * <code>repeated .tr451_vomci_nbi_message.v1.NFInformation.NFCapability capabilities = 2;</code>
     * @param value The capabilities to add.
     * @return This builder for chaining.
     */
    public Builder addCapabilities(org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation.NFCapability value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureCapabilitiesIsMutable();
      capabilities_.add(value.getNumber());
      onChanged();
      return this;
    }
    /**
     * <pre>
     * usage-category, vendor-name,
     * software-version
     * </pre>
     *
     * <code>repeated .tr451_vomci_nbi_message.v1.NFInformation.NFCapability capabilities = 2;</code>
     * @param values The capabilities to add.
     * @return This builder for chaining.
     */
    public Builder addAllCapabilities(
        java.lang.Iterable<? extends org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation.NFCapability> values) {
      ensureCapabilitiesIsMutable();
      for (org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation.NFCapability value : values) {
        capabilities_.add(value.getNumber());
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * usage-category, vendor-name,
     * software-version
     * </pre>
     *
     * <code>repeated .tr451_vomci_nbi_message.v1.NFInformation.NFCapability capabilities = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCapabilities() {
      capabilities_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * usage-category, vendor-name,
     * software-version
     * </pre>
     *
     * <code>repeated .tr451_vomci_nbi_message.v1.NFInformation.NFCapability capabilities = 2;</code>
     * @return A list containing the enum numeric values on the wire for capabilities.
     */
    public java.util.List<java.lang.Integer>
    getCapabilitiesValueList() {
      return java.util.Collections.unmodifiableList(capabilities_);
    }
    /**
     * <pre>
     * usage-category, vendor-name,
     * software-version
     * </pre>
     *
     * <code>repeated .tr451_vomci_nbi_message.v1.NFInformation.NFCapability capabilities = 2;</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of capabilities at the given index.
     */
    public int getCapabilitiesValue(int index) {
      return capabilities_.get(index);
    }
    /**
     * <pre>
     * usage-category, vendor-name,
     * software-version
     * </pre>
     *
     * <code>repeated .tr451_vomci_nbi_message.v1.NFInformation.NFCapability capabilities = 2;</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of capabilities at the given index.
     * @return This builder for chaining.
     */
    public Builder setCapabilitiesValue(
        int index, int value) {
      ensureCapabilitiesIsMutable();
      capabilities_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * usage-category, vendor-name,
     * software-version
     * </pre>
     *
     * <code>repeated .tr451_vomci_nbi_message.v1.NFInformation.NFCapability capabilities = 2;</code>
     * @param value The enum numeric value on the wire for capabilities to add.
     * @return This builder for chaining.
     */
    public Builder addCapabilitiesValue(int value) {
      ensureCapabilitiesIsMutable();
      capabilities_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * usage-category, vendor-name,
     * software-version
     * </pre>
     *
     * <code>repeated .tr451_vomci_nbi_message.v1.NFInformation.NFCapability capabilities = 2;</code>
     * @param values The enum numeric values on the wire for capabilities to add.
     * @return This builder for chaining.
     */
    public Builder addAllCapabilitiesValue(
        java.lang.Iterable<java.lang.Integer> values) {
      ensureCapabilitiesIsMutable();
      for (int value : values) {
        capabilities_.add(value);
      }
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tr451_vomci_nbi_message.v1.NFInformation)
  }

  // @@protoc_insertion_point(class_scope:tr451_vomci_nbi_message.v1.NFInformation)
  private static final org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation();
  }

  public static org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NFInformation>
      PARSER = new com.google.protobuf.AbstractParser<NFInformation>() {
    @java.lang.Override
    public NFInformation parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new NFInformation(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<NFInformation> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NFInformation> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.broadband_forum.obbaa.onu.message.gpb.message.NFInformation getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

