// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tr451_vomci_nbi_message.proto

package org.broadband_forum.obbaa.onu.message.gpb.message;

public interface StatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tr451_vomci_nbi_message.v1.Status)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.tr451_vomci_nbi_message.v1.Status.StatusCode status_code = 1;</code>
   * @return The enum numeric value on the wire for statusCode.
   */
  int getStatusCodeValue();
  /**
   * <code>.tr451_vomci_nbi_message.v1.Status.StatusCode status_code = 1;</code>
   * @return The statusCode.
   */
  org.broadband_forum.obbaa.onu.message.gpb.message.Status.StatusCode getStatusCode();

  /**
   * <pre>
   *Optional: Error information
   * </pre>
   *
   * <code>repeated .tr451_vomci_nbi_message.v1.Error error = 2;</code>
   */
  java.util.List<org.broadband_forum.obbaa.onu.message.gpb.message.Error> 
      getErrorList();
  /**
   * <pre>
   *Optional: Error information
   * </pre>
   *
   * <code>repeated .tr451_vomci_nbi_message.v1.Error error = 2;</code>
   */
  org.broadband_forum.obbaa.onu.message.gpb.message.Error getError(int index);
  /**
   * <pre>
   *Optional: Error information
   * </pre>
   *
   * <code>repeated .tr451_vomci_nbi_message.v1.Error error = 2;</code>
   */
  int getErrorCount();
  /**
   * <pre>
   *Optional: Error information
   * </pre>
   *
   * <code>repeated .tr451_vomci_nbi_message.v1.Error error = 2;</code>
   */
  java.util.List<? extends org.broadband_forum.obbaa.onu.message.gpb.message.ErrorOrBuilder> 
      getErrorOrBuilderList();
  /**
   * <pre>
   *Optional: Error information
   * </pre>
   *
   * <code>repeated .tr451_vomci_nbi_message.v1.Error error = 2;</code>
   */
  org.broadband_forum.obbaa.onu.message.gpb.message.ErrorOrBuilder getErrorOrBuilder(
      int index);
}
