// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tr451_vomci_nbi_message.proto

package org.broadband_forum.obbaa.onu.message.gpb.message;

public final class Tr451VomciNbiMessage {
  private Tr451VomciNbiMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tr451_vomci_nbi_message_v1_Msg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tr451_vomci_nbi_message_v1_Msg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tr451_vomci_nbi_message_v1_Header_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tr451_vomci_nbi_message_v1_Header_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tr451_vomci_nbi_message_v1_Body_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tr451_vomci_nbi_message_v1_Body_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tr451_vomci_nbi_message_v1_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tr451_vomci_nbi_message_v1_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tr451_vomci_nbi_message_v1_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tr451_vomci_nbi_message_v1_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tr451_vomci_nbi_message_v1_Hello_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tr451_vomci_nbi_message_v1_Hello_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tr451_vomci_nbi_message_v1_HelloResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tr451_vomci_nbi_message_v1_HelloResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tr451_vomci_nbi_message_v1_GetData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tr451_vomci_nbi_message_v1_GetData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tr451_vomci_nbi_message_v1_GetDataResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tr451_vomci_nbi_message_v1_GetDataResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tr451_vomci_nbi_message_v1_ReplaceConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tr451_vomci_nbi_message_v1_ReplaceConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tr451_vomci_nbi_message_v1_ReplaceConfigResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tr451_vomci_nbi_message_v1_ReplaceConfigResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tr451_vomci_nbi_message_v1_UpdateConfigReplica_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tr451_vomci_nbi_message_v1_UpdateConfigReplica_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tr451_vomci_nbi_message_v1_UpdateConfigInstance_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tr451_vomci_nbi_message_v1_UpdateConfigInstance_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tr451_vomci_nbi_message_v1_UpdateConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tr451_vomci_nbi_message_v1_UpdateConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tr451_vomci_nbi_message_v1_UpdateConfigResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tr451_vomci_nbi_message_v1_UpdateConfigResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tr451_vomci_nbi_message_v1_RPC_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tr451_vomci_nbi_message_v1_RPC_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tr451_vomci_nbi_message_v1_RPCResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tr451_vomci_nbi_message_v1_RPCResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tr451_vomci_nbi_message_v1_Action_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tr451_vomci_nbi_message_v1_Action_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tr451_vomci_nbi_message_v1_ActionResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tr451_vomci_nbi_message_v1_ActionResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tr451_vomci_nbi_message_v1_Notification_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tr451_vomci_nbi_message_v1_Notification_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tr451_vomci_nbi_message_v1_Error_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tr451_vomci_nbi_message_v1_Error_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tr451_vomci_nbi_message_v1_Status_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tr451_vomci_nbi_message_v1_Status_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035tr451_vomci_nbi_message.proto\022\032tr451_v" +
      "omci_nbi_message.v1\"i\n\003Msg\0222\n\006header\030\001 \001" +
      "(\0132\".tr451_vomci_nbi_message.v1.Header\022." +
      "\n\004body\030\002 \001(\0132 .tr451_vomci_nbi_message.v" +
      "1.Body\"\350\001\n\006Header\022\016\n\006msg_id\030\001 \001(\t\022\023\n\013sen" +
      "der_name\030\002 \001(\t\022\026\n\016recipient_name\030\003 \001(\t\022C" +
      "\n\013object_type\030\004 \001(\0162..tr451_vomci_nbi_me" +
      "ssage.v1.Header.OBJECT_TYPE\022\023\n\013object_na" +
      "me\030\005 \001(\t\"G\n\013OBJECT_TYPE\022\007\n\003ONU\020\000\022\022\n\016VOMC" +
      "I_FUNCTION\020\001\022\017\n\013VOMCI_PROXY\020\002\022\n\n\006VOLTMF\020" +
      "\003\"\306\001\n\004Body\0226\n\007request\030\001 \001(\0132#.tr451_vomc" +
      "i_nbi_message.v1.RequestH\000\0228\n\010response\030\002" +
      " \001(\0132$.tr451_vomci_nbi_message.v1.Respon" +
      "seH\000\022@\n\014notification\030\003 \001(\0132(.tr451_vomci" +
      "_nbi_message.v1.NotificationH\000B\n\n\010msg_bo" +
      "dy\"\360\002\n\007Request\0222\n\005hello\030\002 \001(\0132!.tr451_vo" +
      "mci_nbi_message.v1.HelloH\000\0227\n\010get_data\030\003" +
      " \001(\0132#.tr451_vomci_nbi_message.v1.GetDat" +
      "aH\000\022C\n\016replace_config\030\004 \001(\0132).tr451_vomc" +
      "i_nbi_message.v1.ReplaceConfigH\000\022A\n\rupda" +
      "te_config\030\005 \001(\0132(.tr451_vomci_nbi_messag" +
      "e.v1.UpdateConfigH\000\022.\n\003rpc\030\006 \001(\0132\037.tr451" +
      "_vomci_nbi_message.v1.RPCH\000\0224\n\006action\030\007 " +
      "\001(\0132\".tr451_vomci_nbi_message.v1.ActionH" +
      "\000B\n\n\010req_type\"\243\003\n\010Response\022;\n\nhello_resp" +
      "\030\003 \001(\0132%.tr451_vomci_nbi_message.v1.Hell" +
      "oRespH\000\022;\n\010get_resp\030\004 \001(\0132\'.tr451_vomci_" +
      "nbi_message.v1.GetDataRespH\000\022L\n\023replace_" +
      "config_resp\030\005 \001(\0132-.tr451_vomci_nbi_mess" +
      "age.v1.ReplaceConfigRespH\000\022J\n\022update_con" +
      "fig_resp\030\006 \001(\0132,.tr451_vomci_nbi_message" +
      ".v1.UpdateConfigRespH\000\0227\n\010rpc_resp\030\007 \001(\013" +
      "2#.tr451_vomci_nbi_message.v1.RPCRespH\000\022" +
      "=\n\013action_resp\030\010 \001(\0132&.tr451_vomci_nbi_m" +
      "essage.v1.ActionRespH\000B\013\n\tresp_type\"&\n\005H" +
      "ello\022\035\n\025service_endpoint_name\030\001 \001(\t\"\344\001\n\t" +
      "HelloResp\022\035\n\025service_endpoint_name\030\001 \001(\t" +
      "\022L\n\014capabilities\030\002 \003(\01626.tr451_vomci_nbi" +
      "_message.v1.HelloResp.ServerCapability\"j" +
      "\n\020ServerCapability\022\032\n\026NO_CAPABILITY_REPO" +
      "RTED\020\000\022\032\n\026ONU_STATE_ONLY_SUPPORT\020\001\022\036\n\032ON" +
      "U_CONFIG_REPLICA_SUPPORT\020\002\"\031\n\007GetData\022\016\n" +
      "\006filter\030\001 \003(\014\"T\n\013GetDataResp\0227\n\013status_r" +
      "esp\030\001 \001(\0132\".tr451_vomci_nbi_message.v1.S" +
      "tatus\022\014\n\004data\030\002 \001(\014\"$\n\rReplaceConfig\022\023\n\013" +
      "config_inst\030\001 \001(\014\"L\n\021ReplaceConfigResp\0227" +
      "\n\013status_resp\030\001 \001(\0132\".tr451_vomci_nbi_me" +
      "ssage.v1.Status\"+\n\023UpdateConfigReplica\022\024" +
      "\n\014delta_config\030\001 \001(\014\"I\n\024UpdateConfigInst" +
      "ance\022\033\n\023current_config_inst\030\001 \001(\014\022\024\n\014del" +
      "ta_config\030\002 \001(\014\"\274\001\n\014UpdateConfig\022N\n\022upda" +
      "te_config_inst\030\001 \001(\01320.tr451_vomci_nbi_m" +
      "essage.v1.UpdateConfigInstanceH\000\022P\n\025upda" +
      "te_config_replica\030\002 \001(\0132/.tr451_vomci_nb" +
      "i_message.v1.UpdateConfigReplicaH\000B\n\n\010re" +
      "q_type\"K\n\020UpdateConfigResp\0227\n\013status_res" +
      "p\030\001 \001(\0132\".tr451_vomci_nbi_message.v1.Sta" +
      "tus\"\031\n\003RPC\022\022\n\ninput_data\030\001 \001(\014\"W\n\007RPCRes" +
      "p\0227\n\013status_resp\030\001 \001(\0132\".tr451_vomci_nbi" +
      "_message.v1.Status\022\023\n\013output_data\030\002 \001(\014\"" +
      "\034\n\006Action\022\022\n\ninput_data\030\001 \001(\014\"Z\n\nActionR" +
      "esp\0227\n\013status_resp\030\001 \001(\0132\".tr451_vomci_n" +
      "bi_message.v1.Status\022\023\n\013output_data\030\002 \001(" +
      "\014\"\034\n\014Notification\022\014\n\004data\030\001 \001(\014\"\210\001\n\005Erro" +
      "r\022\022\n\nerror_type\030\001 \001(\t\022\021\n\terror_tag\030\002 \001(\t" +
      "\022\026\n\016error_severity\030\003 \001(\t\022\025\n\rerror_app_ta" +
      "g\030\004 \001(\t\022\022\n\nerror_path\030\005 \001(\t\022\025\n\rerror_mes" +
      "sage\030\006 \001(\t\"\247\001\n\006Status\022B\n\013status_code\030\001 \001" +
      "(\0162-.tr451_vomci_nbi_message.v1.Status.S" +
      "tatusCode\0220\n\005error\030\002 \003(\0132!.tr451_vomci_n" +
      "bi_message.v1.Error\"\'\n\nStatusCode\022\006\n\002OK\020" +
      "\000\022\021\n\rERROR_GENERAL\020\001B5\n1org.broadband_fo" +
      "rum.obbaa.onu.message.gpb.messageP\001b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tr451_vomci_nbi_message_v1_Msg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tr451_vomci_nbi_message_v1_Msg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tr451_vomci_nbi_message_v1_Msg_descriptor,
        new java.lang.String[] { "Header", "Body", });
    internal_static_tr451_vomci_nbi_message_v1_Header_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tr451_vomci_nbi_message_v1_Header_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tr451_vomci_nbi_message_v1_Header_descriptor,
        new java.lang.String[] { "MsgId", "SenderName", "RecipientName", "ObjectType", "ObjectName", });
    internal_static_tr451_vomci_nbi_message_v1_Body_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_tr451_vomci_nbi_message_v1_Body_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tr451_vomci_nbi_message_v1_Body_descriptor,
        new java.lang.String[] { "Request", "Response", "Notification", "MsgBody", });
    internal_static_tr451_vomci_nbi_message_v1_Request_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_tr451_vomci_nbi_message_v1_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tr451_vomci_nbi_message_v1_Request_descriptor,
        new java.lang.String[] { "Hello", "GetData", "ReplaceConfig", "UpdateConfig", "Rpc", "Action", "ReqType", });
    internal_static_tr451_vomci_nbi_message_v1_Response_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_tr451_vomci_nbi_message_v1_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tr451_vomci_nbi_message_v1_Response_descriptor,
        new java.lang.String[] { "HelloResp", "GetResp", "ReplaceConfigResp", "UpdateConfigResp", "RpcResp", "ActionResp", "RespType", });
    internal_static_tr451_vomci_nbi_message_v1_Hello_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_tr451_vomci_nbi_message_v1_Hello_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tr451_vomci_nbi_message_v1_Hello_descriptor,
        new java.lang.String[] { "ServiceEndpointName", });
    internal_static_tr451_vomci_nbi_message_v1_HelloResp_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_tr451_vomci_nbi_message_v1_HelloResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tr451_vomci_nbi_message_v1_HelloResp_descriptor,
        new java.lang.String[] { "ServiceEndpointName", "Capabilities", });
    internal_static_tr451_vomci_nbi_message_v1_GetData_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_tr451_vomci_nbi_message_v1_GetData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tr451_vomci_nbi_message_v1_GetData_descriptor,
        new java.lang.String[] { "Filter", });
    internal_static_tr451_vomci_nbi_message_v1_GetDataResp_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_tr451_vomci_nbi_message_v1_GetDataResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tr451_vomci_nbi_message_v1_GetDataResp_descriptor,
        new java.lang.String[] { "StatusResp", "Data", });
    internal_static_tr451_vomci_nbi_message_v1_ReplaceConfig_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_tr451_vomci_nbi_message_v1_ReplaceConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tr451_vomci_nbi_message_v1_ReplaceConfig_descriptor,
        new java.lang.String[] { "ConfigInst", });
    internal_static_tr451_vomci_nbi_message_v1_ReplaceConfigResp_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_tr451_vomci_nbi_message_v1_ReplaceConfigResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tr451_vomci_nbi_message_v1_ReplaceConfigResp_descriptor,
        new java.lang.String[] { "StatusResp", });
    internal_static_tr451_vomci_nbi_message_v1_UpdateConfigReplica_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_tr451_vomci_nbi_message_v1_UpdateConfigReplica_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tr451_vomci_nbi_message_v1_UpdateConfigReplica_descriptor,
        new java.lang.String[] { "DeltaConfig", });
    internal_static_tr451_vomci_nbi_message_v1_UpdateConfigInstance_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_tr451_vomci_nbi_message_v1_UpdateConfigInstance_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tr451_vomci_nbi_message_v1_UpdateConfigInstance_descriptor,
        new java.lang.String[] { "CurrentConfigInst", "DeltaConfig", });
    internal_static_tr451_vomci_nbi_message_v1_UpdateConfig_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_tr451_vomci_nbi_message_v1_UpdateConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tr451_vomci_nbi_message_v1_UpdateConfig_descriptor,
        new java.lang.String[] { "UpdateConfigInst", "UpdateConfigReplica", "ReqType", });
    internal_static_tr451_vomci_nbi_message_v1_UpdateConfigResp_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_tr451_vomci_nbi_message_v1_UpdateConfigResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tr451_vomci_nbi_message_v1_UpdateConfigResp_descriptor,
        new java.lang.String[] { "StatusResp", });
    internal_static_tr451_vomci_nbi_message_v1_RPC_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_tr451_vomci_nbi_message_v1_RPC_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tr451_vomci_nbi_message_v1_RPC_descriptor,
        new java.lang.String[] { "InputData", });
    internal_static_tr451_vomci_nbi_message_v1_RPCResp_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_tr451_vomci_nbi_message_v1_RPCResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tr451_vomci_nbi_message_v1_RPCResp_descriptor,
        new java.lang.String[] { "StatusResp", "OutputData", });
    internal_static_tr451_vomci_nbi_message_v1_Action_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_tr451_vomci_nbi_message_v1_Action_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tr451_vomci_nbi_message_v1_Action_descriptor,
        new java.lang.String[] { "InputData", });
    internal_static_tr451_vomci_nbi_message_v1_ActionResp_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_tr451_vomci_nbi_message_v1_ActionResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tr451_vomci_nbi_message_v1_ActionResp_descriptor,
        new java.lang.String[] { "StatusResp", "OutputData", });
    internal_static_tr451_vomci_nbi_message_v1_Notification_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_tr451_vomci_nbi_message_v1_Notification_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tr451_vomci_nbi_message_v1_Notification_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_tr451_vomci_nbi_message_v1_Error_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_tr451_vomci_nbi_message_v1_Error_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tr451_vomci_nbi_message_v1_Error_descriptor,
        new java.lang.String[] { "ErrorType", "ErrorTag", "ErrorSeverity", "ErrorAppTag", "ErrorPath", "ErrorMessage", });
    internal_static_tr451_vomci_nbi_message_v1_Status_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_tr451_vomci_nbi_message_v1_Status_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tr451_vomci_nbi_message_v1_Status_descriptor,
        new java.lang.String[] { "StatusCode", "Error", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
