// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tr451_vomci_nbi_message.proto

package org.broadband_forum.obbaa.onu.message.gpb.message;

public interface UpdateConfigRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tr451_vomci_nbi_message.v1.UpdateConfigResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.tr451_vomci_nbi_message.v1.Status status_resp = 1;</code>
   * @return Whether the statusResp field is set.
   */
  boolean hasStatusResp();
  /**
   * <code>.tr451_vomci_nbi_message.v1.Status status_resp = 1;</code>
   * @return The statusResp.
   */
  org.broadband_forum.obbaa.onu.message.gpb.message.Status getStatusResp();
  /**
   * <code>.tr451_vomci_nbi_message.v1.Status status_resp = 1;</code>
   */
  org.broadband_forum.obbaa.onu.message.gpb.message.StatusOrBuilder getStatusRespOrBuilder();
}
