// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tr451_vomci_nbi_message.proto

package org.broadband_forum.obbaa.onu.message.gpb.message;

public interface UpdateConfigReplicaOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tr451_vomci_nbi_message.v1.UpdateConfigReplica)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * List of Node changes with the
   * </pre>
   *
   * <code>bytes delta_config = 1;</code>
   * @return The deltaConfig.
   */
  com.google.protobuf.ByteString getDeltaConfig();
}
