apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: obbaa
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: NodePort
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: {{ .Values.nodePort }}
    protocol: TCP
  selector:
    app: {{ .Chart.Name }}