// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tr451_vomci_nbi_message.proto

package org.broadband_forum.obbaa.onu.pm.message.gpb.message;

public interface ActionOrBuilder extends
        // @@protoc_insertion_point(interface_extends:tr451_vomci_nbi_message.v1.Action)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes input_data = 1;</code>
     *
     * @return The inputData.
     */
    com.google.protobuf.ByteString getInputData();

    /**
     * <pre>
     * Optional: Datastore tag used to
     * </pre>
     *
     * <code>string datastore_tag = 2;</code>
     *
     * @return The datastoreTag.
     */
    java.lang.String getDatastoreTag();

    /**
     * <pre>
     * Optional: Datastore tag used to
     * </pre>
     *
     * <code>string datastore_tag = 2;</code>
     *
     * @return The bytes for datastoreTag.
     */
    com.google.protobuf.ByteString
    getDatastoreTagBytes();
}
