// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tr451_vomci_nbi_message.proto

package org.broadband_forum.obbaa.onu.pm.message.gpb.message;

/**
 * Protobuf type {@code tr451_vomci_nbi_message.v1.Response}
 */
public final class Response extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:tr451_vomci_nbi_message.v1.Response)
        ResponseOrBuilder {
    public static final int HELLO_RESP_FIELD_NUMBER = 3;
    public static final int GET_RESP_FIELD_NUMBER = 4;
    public static final int REPLACE_CONFIG_RESP_FIELD_NUMBER = 5;
    public static final int UPDATE_CONFIG_RESP_FIELD_NUMBER = 6;
    public static final int RPC_RESP_FIELD_NUMBER = 7;
    public static final int ACTION_RESP_FIELD_NUMBER = 8;
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:tr451_vomci_nbi_message.v1.Response)
    private static final org.broadband_forum.obbaa.onu.pm.message.gpb.message.Response DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<Response>
            PARSER = new com.google.protobuf.AbstractParser<Response>() {
        @java.lang.Override
        public Response parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new Response(input, extensionRegistry);
        }
    };

    static {
        DEFAULT_INSTANCE = new org.broadband_forum.obbaa.onu.pm.message.gpb.message.Response();
    }

    private int respTypeCase_ = 0;

    private java.lang.Object respType_;
    private byte memoizedIsInitialized = -1;

    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private Response() {
    }

    private Response(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    case 26: {
                        org.broadband_forum.obbaa.onu.pm.message.gpb.message.HelloResp.Builder subBuilder = null;
                        if (respTypeCase_ == 3) {
                            subBuilder = ((org.broadband_forum.obbaa.onu.pm.message.gpb.message.HelloResp) respType_).toBuilder();
                        }
                        respType_ =
                                input.readMessage(org.broadband_forum.obbaa.onu.pm.message.gpb.message.HelloResp.parser(), extensionRegistry);
                        if (subBuilder != null) {
                            subBuilder.mergeFrom((org.broadband_forum.obbaa.onu.pm.message.gpb.message.HelloResp) respType_);
                            respType_ = subBuilder.buildPartial();
                        }
                        respTypeCase_ = 3;
                        break;
                    }
                    case 34: {
                        org.broadband_forum.obbaa.onu.pm.message.gpb.message.GetDataResp.Builder subBuilder = null;
                        if (respTypeCase_ == 4) {
                            subBuilder = ((org.broadband_forum.obbaa.onu.pm.message.gpb.message.GetDataResp) respType_).toBuilder();
                        }
                        respType_ =
                                input.readMessage(org.broadband_forum.obbaa.onu.pm.message.gpb.message.GetDataResp.parser(), extensionRegistry);
                        if (subBuilder != null) {
                            subBuilder.mergeFrom((org.broadband_forum.obbaa.onu.pm.message.gpb.message.GetDataResp) respType_);
                            respType_ = subBuilder.buildPartial();
                        }
                        respTypeCase_ = 4;
                        break;
                    }
                    case 42: {
                        org.broadband_forum.obbaa.onu.pm.message.gpb.message.ReplaceConfigResp.Builder subBuilder = null;
                        if (respTypeCase_ == 5) {
                            subBuilder = ((org.broadband_forum.obbaa.onu.pm.message.gpb.message.ReplaceConfigResp) respType_).toBuilder();
                        }
                        respType_ =
                                input.readMessage(org.broadband_forum.obbaa.onu.pm.message.gpb.message.ReplaceConfigResp.parser(), extensionRegistry);
                        if (subBuilder != null) {
                            subBuilder.mergeFrom((org.broadband_forum.obbaa.onu.pm.message.gpb.message.ReplaceConfigResp) respType_);
                            respType_ = subBuilder.buildPartial();
                        }
                        respTypeCase_ = 5;
                        break;
                    }
                    case 50: {
                        org.broadband_forum.obbaa.onu.pm.message.gpb.message.UpdateConfigResp.Builder subBuilder = null;
                        if (respTypeCase_ == 6) {
                            subBuilder = ((org.broadband_forum.obbaa.onu.pm.message.gpb.message.UpdateConfigResp) respType_).toBuilder();
                        }
                        respType_ =
                                input.readMessage(org.broadband_forum.obbaa.onu.pm.message.gpb.message.UpdateConfigResp.parser(), extensionRegistry);
                        if (subBuilder != null) {
                            subBuilder.mergeFrom((org.broadband_forum.obbaa.onu.pm.message.gpb.message.UpdateConfigResp) respType_);
                            respType_ = subBuilder.buildPartial();
                        }
                        respTypeCase_ = 6;
                        break;
                    }
                    case 58: {
                        org.broadband_forum.obbaa.onu.pm.message.gpb.message.RPCResp.Builder subBuilder = null;
                        if (respTypeCase_ == 7) {
                            subBuilder = ((org.broadband_forum.obbaa.onu.pm.message.gpb.message.RPCResp) respType_).toBuilder();
                        }
                        respType_ =
                                input.readMessage(org.broadband_forum.obbaa.onu.pm.message.gpb.message.RPCResp.parser(), extensionRegistry);
                        if (subBuilder != null) {
                            subBuilder.mergeFrom((org.broadband_forum.obbaa.onu.pm.message.gpb.message.RPCResp) respType_);
                            respType_ = subBuilder.buildPartial();
                        }
                        respTypeCase_ = 7;
                        break;
                    }
                    case 66: {
                        org.broadband_forum.obbaa.onu.pm.message.gpb.message.ActionResp.Builder subBuilder = null;
                        if (respTypeCase_ == 8) {
                            subBuilder = ((org.broadband_forum.obbaa.onu.pm.message.gpb.message.ActionResp) respType_).toBuilder();
                        }
                        respType_ =
                                input.readMessage(org.broadband_forum.obbaa.onu.pm.message.gpb.message.ActionResp.parser(), extensionRegistry);
                        if (subBuilder != null) {
                            subBuilder.mergeFrom((org.broadband_forum.obbaa.onu.pm.message.gpb.message.ActionResp) respType_);
                            respType_ = subBuilder.buildPartial();
                        }
                        respTypeCase_ = 8;
                        break;
                    }
                    default: {
                        if (!parseUnknownField(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return org.broadband_forum.obbaa.onu.pm.message.gpb.message.Tr451VomciNbiMessage.internal_static_tr451_vomci_nbi_message_v1_Response_descriptor;
    }

    public static org.broadband_forum.obbaa.onu.pm.message.gpb.message.Response parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static org.broadband_forum.obbaa.onu.pm.message.gpb.message.Response parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static org.broadband_forum.obbaa.onu.pm.message.gpb.message.Response parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static org.broadband_forum.obbaa.onu.pm.message.gpb.message.Response parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static org.broadband_forum.obbaa.onu.pm.message.gpb.message.Response parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static org.broadband_forum.obbaa.onu.pm.message.gpb.message.Response parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static org.broadband_forum.obbaa.onu.pm.message.gpb.message.Response parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static org.broadband_forum.obbaa.onu.pm.message.gpb.message.Response parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.broadband_forum.obbaa.onu.pm.message.gpb.message.Response parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.broadband_forum.obbaa.onu.pm.message.gpb.message.Response parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.broadband_forum.obbaa.onu.pm.message.gpb.message.Response parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static org.broadband_forum.obbaa.onu.pm.message.gpb.message.Response parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(org.broadband_forum.obbaa.onu.pm.message.gpb.message.Response prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static org.broadband_forum.obbaa.onu.pm.message.gpb.message.Response getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<Response> parser() {
        return PARSER;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
        return new Response();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return org.broadband_forum.obbaa.onu.pm.message.gpb.message.Tr451VomciNbiMessage.internal_static_tr451_vomci_nbi_message_v1_Response_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        org.broadband_forum.obbaa.onu.pm.message.gpb.message.Response.class, org.broadband_forum.obbaa.onu.pm.message.gpb.message.Response.Builder.class);
    }

    public RespTypeCase
    getRespTypeCase() {
        return RespTypeCase.forNumber(
                respTypeCase_);
    }

    /**
     * <code>.tr451_vomci_nbi_message.v1.HelloResp hello_resp = 3;</code>
     *
     * @return Whether the helloResp field is set.
     */
    public boolean hasHelloResp() {
        return respTypeCase_ == 3;
    }

    /**
     * <code>.tr451_vomci_nbi_message.v1.HelloResp hello_resp = 3;</code>
     *
     * @return The helloResp.
     */
    public org.broadband_forum.obbaa.onu.pm.message.gpb.message.HelloResp getHelloResp() {
        if (respTypeCase_ == 3) {
            return (org.broadband_forum.obbaa.onu.pm.message.gpb.message.HelloResp) respType_;
        }
        return org.broadband_forum.obbaa.onu.pm.message.gpb.message.HelloResp.getDefaultInstance();
    }

    /**
     * <code>.tr451_vomci_nbi_message.v1.HelloResp hello_resp = 3;</code>
     */
    public org.broadband_forum.obbaa.onu.pm.message.gpb.message.HelloRespOrBuilder getHelloRespOrBuilder() {
        if (respTypeCase_ == 3) {
            return (org.broadband_forum.obbaa.onu.pm.message.gpb.message.HelloResp) respType_;
        }
        return org.broadband_forum.obbaa.onu.pm.message.gpb.message.HelloResp.getDefaultInstance();
    }

    /**
     * <code>.tr451_vomci_nbi_message.v1.GetDataResp get_resp = 4;</code>
     *
     * @return Whether the getResp field is set.
     */
    public boolean hasGetResp() {
        return respTypeCase_ == 4;
    }

    /**
     * <code>.tr451_vomci_nbi_message.v1.GetDataResp get_resp = 4;</code>
     *
     * @return The getResp.
     */
    public org.broadband_forum.obbaa.onu.pm.message.gpb.message.GetDataResp getGetResp() {
        if (respTypeCase_ == 4) {
            return (org.broadband_forum.obbaa.onu.pm.message.gpb.message.GetDataResp) respType_;
        }
        return org.broadband_forum.obbaa.onu.pm.message.gpb.message.GetDataResp.getDefaultInstance();
    }

    /**
     * <code>.tr451_vomci_nbi_message.v1.GetDataResp get_resp = 4;</code>
     */
    public org.broadband_forum.obbaa.onu.pm.message.gpb.message.GetDataRespOrBuilder getGetRespOrBuilder() {
        if (respTypeCase_ == 4) {
            return (org.broadband_forum.obbaa.onu.pm.message.gpb.message.GetDataResp) respType_;
        }
        return org.broadband_forum.obbaa.onu.pm.message.gpb.message.GetDataResp.getDefaultInstance();
    }

    /**
     * <code>.tr451_vomci_nbi_message.v1.ReplaceConfigResp replace_config_resp = 5;</code>
     *
     * @return Whether the replaceConfigResp field is set.
     */
    public boolean hasReplaceConfigResp() {
        return respTypeCase_ == 5;
    }

    /**
     * <code>.tr451_vomci_nbi_message.v1.ReplaceConfigResp replace_config_resp = 5;</code>
     *
     * @return The replaceConfigResp.
     */
    public org.broadband_forum.obbaa.onu.pm.message.gpb.message.ReplaceConfigResp getReplaceConfigResp() {
        if (respTypeCase_ == 5) {
            return (org.broadband_forum.obbaa.onu.pm.message.gpb.message.ReplaceConfigResp) respType_;
        }
        return org.broadband_forum.obbaa.onu.pm.message.gpb.message.ReplaceConfigResp.getDefaultInstance();
    }

    /**
     * <code>.tr451_vomci_nbi_message.v1.ReplaceConfigResp replace_config_resp = 5;</code>
     */
    public org.broadband_forum.obbaa.onu.pm.message.gpb.message.ReplaceConfigRespOrBuilder getReplaceConfigRespOrBuilder() {
        if (respTypeCase_ == 5) {
            return (org.broadband_forum.obbaa.onu.pm.message.gpb.message.ReplaceConfigResp) respType_;
        }
        return org.broadband_forum.obbaa.onu.pm.message.gpb.message.ReplaceConfigResp.getDefaultInstance();
    }

    /**
     * <code>.tr451_vomci_nbi_message.v1.UpdateConfigResp update_config_resp = 6;</code>
     *
     * @return Whether the updateConfigResp field is set.
     */
    public boolean hasUpdateConfigResp() {
        return respTypeCase_ == 6;
    }

    /**
     * <code>.tr451_vomci_nbi_message.v1.UpdateConfigResp update_config_resp = 6;</code>
     *
     * @return The updateConfigResp.
     */
    public org.broadband_forum.obbaa.onu.pm.message.gpb.message.UpdateConfigResp getUpdateConfigResp() {
        if (respTypeCase_ == 6) {
            return (org.broadband_forum.obbaa.onu.pm.message.gpb.message.UpdateConfigResp) respType_;
        }
        return org.broadband_forum.obbaa.onu.pm.message.gpb.message.UpdateConfigResp.getDefaultInstance();
    }

    /**
     * <code>.tr451_vomci_nbi_message.v1.UpdateConfigResp update_config_resp = 6;</code>
     */
    public org.broadband_forum.obbaa.onu.pm.message.gpb.message.UpdateConfigRespOrBuilder getUpdateConfigRespOrBuilder() {
        if (respTypeCase_ == 6) {
            return (org.broadband_forum.obbaa.onu.pm.message.gpb.message.UpdateConfigResp) respType_;
        }
        return org.broadband_forum.obbaa.onu.pm.message.gpb.message.UpdateConfigResp.getDefaultInstance();
    }

    /**
     * <code>.tr451_vomci_nbi_message.v1.RPCResp rpc_resp = 7;</code>
     *
     * @return Whether the rpcResp field is set.
     */
    public boolean hasRpcResp() {
        return respTypeCase_ == 7;
    }

    /**
     * <code>.tr451_vomci_nbi_message.v1.RPCResp rpc_resp = 7;</code>
     *
     * @return The rpcResp.
     */
    public org.broadband_forum.obbaa.onu.pm.message.gpb.message.RPCResp getRpcResp() {
        if (respTypeCase_ == 7) {
            return (org.broadband_forum.obbaa.onu.pm.message.gpb.message.RPCResp) respType_;
        }
        return org.broadband_forum.obbaa.onu.pm.message.gpb.message.RPCResp.getDefaultInstance();
    }

    /**
     * <code>.tr451_vomci_nbi_message.v1.RPCResp rpc_resp = 7;</code>
     */
    public org.broadband_forum.obbaa.onu.pm.message.gpb.message.RPCRespOrBuilder getRpcRespOrBuilder() {
        if (respTypeCase_ == 7) {
            return (org.broadband_forum.obbaa.onu.pm.message.gpb.message.RPCResp) respType_;
        }
        return org.broadband_forum.obbaa.onu.pm.message.gpb.message.RPCResp.getDefaultInstance();
    }

    /**
     * <code>.tr451_vomci_nbi_message.v1.ActionResp action_resp = 8;</code>
     *
     * @return Whether the actionResp field is set.
     */
    public boolean hasActionResp() {
        return respTypeCase_ == 8;
    }

    /**
     * <code>.tr451_vomci_nbi_message.v1.ActionResp action_resp = 8;</code>
     *
     * @return The actionResp.
     */
    public org.broadband_forum.obbaa.onu.pm.message.gpb.message.ActionResp getActionResp() {
        if (respTypeCase_ == 8) {
            return (org.broadband_forum.obbaa.onu.pm.message.gpb.message.ActionResp) respType_;
        }
        return org.broadband_forum.obbaa.onu.pm.message.gpb.message.ActionResp.getDefaultInstance();
    }

    /**
     * <code>.tr451_vomci_nbi_message.v1.ActionResp action_resp = 8;</code>
     */
    public org.broadband_forum.obbaa.onu.pm.message.gpb.message.ActionRespOrBuilder getActionRespOrBuilder() {
        if (respTypeCase_ == 8) {
            return (org.broadband_forum.obbaa.onu.pm.message.gpb.message.ActionResp) respType_;
        }
        return org.broadband_forum.obbaa.onu.pm.message.gpb.message.ActionResp.getDefaultInstance();
    }

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (respTypeCase_ == 3) {
            output.writeMessage(3, (org.broadband_forum.obbaa.onu.pm.message.gpb.message.HelloResp) respType_);
        }
        if (respTypeCase_ == 4) {
            output.writeMessage(4, (org.broadband_forum.obbaa.onu.pm.message.gpb.message.GetDataResp) respType_);
        }
        if (respTypeCase_ == 5) {
            output.writeMessage(5, (org.broadband_forum.obbaa.onu.pm.message.gpb.message.ReplaceConfigResp) respType_);
        }
        if (respTypeCase_ == 6) {
            output.writeMessage(6, (org.broadband_forum.obbaa.onu.pm.message.gpb.message.UpdateConfigResp) respType_);
        }
        if (respTypeCase_ == 7) {
            output.writeMessage(7, (org.broadband_forum.obbaa.onu.pm.message.gpb.message.RPCResp) respType_);
        }
        if (respTypeCase_ == 8) {
            output.writeMessage(8, (org.broadband_forum.obbaa.onu.pm.message.gpb.message.ActionResp) respType_);
        }
        unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (respTypeCase_ == 3) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(3, (org.broadband_forum.obbaa.onu.pm.message.gpb.message.HelloResp) respType_);
        }
        if (respTypeCase_ == 4) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(4, (org.broadband_forum.obbaa.onu.pm.message.gpb.message.GetDataResp) respType_);
        }
        if (respTypeCase_ == 5) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(5, (org.broadband_forum.obbaa.onu.pm.message.gpb.message.ReplaceConfigResp) respType_);
        }
        if (respTypeCase_ == 6) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(6, (org.broadband_forum.obbaa.onu.pm.message.gpb.message.UpdateConfigResp) respType_);
        }
        if (respTypeCase_ == 7) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(7, (org.broadband_forum.obbaa.onu.pm.message.gpb.message.RPCResp) respType_);
        }
        if (respTypeCase_ == 8) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(8, (org.broadband_forum.obbaa.onu.pm.message.gpb.message.ActionResp) respType_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof org.broadband_forum.obbaa.onu.pm.message.gpb.message.Response)) {
            return super.equals(obj);
        }
        org.broadband_forum.obbaa.onu.pm.message.gpb.message.Response other = (org.broadband_forum.obbaa.onu.pm.message.gpb.message.Response) obj;

        if (!getRespTypeCase().equals(other.getRespTypeCase())) return false;
        switch (respTypeCase_) {
            case 3:
                if (!getHelloResp()
                        .equals(other.getHelloResp())) return false;
                break;
            case 4:
                if (!getGetResp()
                        .equals(other.getGetResp())) return false;
                break;
            case 5:
                if (!getReplaceConfigResp()
                        .equals(other.getReplaceConfigResp())) return false;
                break;
            case 6:
                if (!getUpdateConfigResp()
                        .equals(other.getUpdateConfigResp())) return false;
                break;
            case 7:
                if (!getRpcResp()
                        .equals(other.getRpcResp())) return false;
                break;
            case 8:
                if (!getActionResp()
                        .equals(other.getActionResp())) return false;
                break;
            case 0:
            default:
        }
        return unknownFields.equals(other.unknownFields);
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        switch (respTypeCase_) {
            case 3:
                hash = (37 * hash) + HELLO_RESP_FIELD_NUMBER;
                hash = (53 * hash) + getHelloResp().hashCode();
                break;
            case 4:
                hash = (37 * hash) + GET_RESP_FIELD_NUMBER;
                hash = (53 * hash) + getGetResp().hashCode();
                break;
            case 5:
                hash = (37 * hash) + REPLACE_CONFIG_RESP_FIELD_NUMBER;
                hash = (53 * hash) + getReplaceConfigResp().hashCode();
                break;
            case 6:
                hash = (37 * hash) + UPDATE_CONFIG_RESP_FIELD_NUMBER;
                hash = (53 * hash) + getUpdateConfigResp().hashCode();
                break;
            case 7:
                hash = (37 * hash) + RPC_RESP_FIELD_NUMBER;
                hash = (53 * hash) + getRpcResp().hashCode();
                break;
            case 8:
                hash = (37 * hash) + ACTION_RESP_FIELD_NUMBER;
                hash = (53 * hash) + getActionResp().hashCode();
                break;
            case 0:
            default:
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public org.broadband_forum.obbaa.onu.pm.message.gpb.message.Response getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

    public enum RespTypeCase
            implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
        HELLO_RESP(3),
        GET_RESP(4),
        REPLACE_CONFIG_RESP(5),
        UPDATE_CONFIG_RESP(6),
        RPC_RESP(7),
        ACTION_RESP(8),
        RESPTYPE_NOT_SET(0);
        private final int value;

        RespTypeCase(int value) {
            this.value = value;
        }

        /**
         * @param value The number of the enum to look for.
         * @return The enum associated with the given number.
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @java.lang.Deprecated
        public static RespTypeCase valueOf(int value) {
            return forNumber(value);
        }

        public static RespTypeCase forNumber(int value) {
            switch (value) {
                case 3:
                    return HELLO_RESP;
                case 4:
                    return GET_RESP;
                case 5:
                    return REPLACE_CONFIG_RESP;
                case 6:
                    return UPDATE_CONFIG_RESP;
                case 7:
                    return RPC_RESP;
                case 8:
                    return ACTION_RESP;
                case 0:
                    return RESPTYPE_NOT_SET;
                default:
                    return null;
            }
        }

        public int getNumber() {
            return this.value;
        }
    }

    /**
     * Protobuf type {@code tr451_vomci_nbi_message.v1.Response}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:tr451_vomci_nbi_message.v1.Response)
            org.broadband_forum.obbaa.onu.pm.message.gpb.message.ResponseOrBuilder {
        private int respTypeCase_ = 0;
        private java.lang.Object respType_;
        private com.google.protobuf.SingleFieldBuilderV3<
                org.broadband_forum.obbaa.onu.pm.message.gpb.message.HelloResp, org.broadband_forum.obbaa.onu.pm.message.gpb.message.HelloResp.Builder, org.broadband_forum.obbaa.onu.pm.message.gpb.message.HelloRespOrBuilder> helloRespBuilder_;
        private com.google.protobuf.SingleFieldBuilderV3<
                org.broadband_forum.obbaa.onu.pm.message.gpb.message.GetDataResp, org.broadband_forum.obbaa.onu.pm.message.gpb.message.GetDataResp.Builder, org.broadband_forum.obbaa.onu.pm.message.gpb.message.GetDataRespOrBuilder> getRespBuilder_;
        private com.google.protobuf.SingleFieldBuilderV3<
                org.broadband_forum.obbaa.onu.pm.message.gpb.message.ReplaceConfigResp, org.broadband_forum.obbaa.onu.pm.message.gpb.message.ReplaceConfigResp.Builder, org.broadband_forum.obbaa.onu.pm.message.gpb.message.ReplaceConfigRespOrBuilder> replaceConfigRespBuilder_;
        private com.google.protobuf.SingleFieldBuilderV3<
                org.broadband_forum.obbaa.onu.pm.message.gpb.message.UpdateConfigResp, org.broadband_forum.obbaa.onu.pm.message.gpb.message.UpdateConfigResp.Builder, org.broadband_forum.obbaa.onu.pm.message.gpb.message.UpdateConfigRespOrBuilder> updateConfigRespBuilder_;
        private com.google.protobuf.SingleFieldBuilderV3<
                org.broadband_forum.obbaa.onu.pm.message.gpb.message.RPCResp, org.broadband_forum.obbaa.onu.pm.message.gpb.message.RPCResp.Builder, org.broadband_forum.obbaa.onu.pm.message.gpb.message.RPCRespOrBuilder> rpcRespBuilder_;
        private com.google.protobuf.SingleFieldBuilderV3<
                org.broadband_forum.obbaa.onu.pm.message.gpb.message.ActionResp, org.broadband_forum.obbaa.onu.pm.message.gpb.message.ActionResp.Builder, org.broadband_forum.obbaa.onu.pm.message.gpb.message.ActionRespOrBuilder> actionRespBuilder_;

        // Construct using org.broadband_forum.obbaa.onu.pm.message.gpb.message.Response.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return org.broadband_forum.obbaa.onu.pm.message.gpb.message.Tr451VomciNbiMessage.internal_static_tr451_vomci_nbi_message_v1_Response_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return org.broadband_forum.obbaa.onu.pm.message.gpb.message.Tr451VomciNbiMessage.internal_static_tr451_vomci_nbi_message_v1_Response_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            org.broadband_forum.obbaa.onu.pm.message.gpb.message.Response.class, org.broadband_forum.obbaa.onu.pm.message.gpb.message.Response.Builder.class);
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            respTypeCase_ = 0;
            respType_ = null;
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return org.broadband_forum.obbaa.onu.pm.message.gpb.message.Tr451VomciNbiMessage.internal_static_tr451_vomci_nbi_message_v1_Response_descriptor;
        }

        @java.lang.Override
        public org.broadband_forum.obbaa.onu.pm.message.gpb.message.Response getDefaultInstanceForType() {
            return org.broadband_forum.obbaa.onu.pm.message.gpb.message.Response.getDefaultInstance();
        }

        @java.lang.Override
        public org.broadband_forum.obbaa.onu.pm.message.gpb.message.Response build() {
            org.broadband_forum.obbaa.onu.pm.message.gpb.message.Response result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public org.broadband_forum.obbaa.onu.pm.message.gpb.message.Response buildPartial() {
            org.broadband_forum.obbaa.onu.pm.message.gpb.message.Response result = new org.broadband_forum.obbaa.onu.pm.message.gpb.message.Response(this);
            if (respTypeCase_ == 3) {
                if (helloRespBuilder_ == null) {
                    result.respType_ = respType_;
                } else {
                    result.respType_ = helloRespBuilder_.build();
                }
            }
            if (respTypeCase_ == 4) {
                if (getRespBuilder_ == null) {
                    result.respType_ = respType_;
                } else {
                    result.respType_ = getRespBuilder_.build();
                }
            }
            if (respTypeCase_ == 5) {
                if (replaceConfigRespBuilder_ == null) {
                    result.respType_ = respType_;
                } else {
                    result.respType_ = replaceConfigRespBuilder_.build();
                }
            }
            if (respTypeCase_ == 6) {
                if (updateConfigRespBuilder_ == null) {
                    result.respType_ = respType_;
                } else {
                    result.respType_ = updateConfigRespBuilder_.build();
                }
            }
            if (respTypeCase_ == 7) {
                if (rpcRespBuilder_ == null) {
                    result.respType_ = respType_;
                } else {
                    result.respType_ = rpcRespBuilder_.build();
                }
            }
            if (respTypeCase_ == 8) {
                if (actionRespBuilder_ == null) {
                    result.respType_ = respType_;
                } else {
                    result.respType_ = actionRespBuilder_.build();
                }
            }
            result.respTypeCase_ = respTypeCase_;
            onBuilt();
            return result;
        }

        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }

        @java.lang.Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.setField(field, value);
        }

        @java.lang.Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @java.lang.Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @java.lang.Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof org.broadband_forum.obbaa.onu.pm.message.gpb.message.Response) {
                return mergeFrom((org.broadband_forum.obbaa.onu.pm.message.gpb.message.Response) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(org.broadband_forum.obbaa.onu.pm.message.gpb.message.Response other) {
            if (other == org.broadband_forum.obbaa.onu.pm.message.gpb.message.Response.getDefaultInstance())
                return this;
            switch (other.getRespTypeCase()) {
                case HELLO_RESP: {
                    mergeHelloResp(other.getHelloResp());
                    break;
                }
                case GET_RESP: {
                    mergeGetResp(other.getGetResp());
                    break;
                }
                case REPLACE_CONFIG_RESP: {
                    mergeReplaceConfigResp(other.getReplaceConfigResp());
                    break;
                }
                case UPDATE_CONFIG_RESP: {
                    mergeUpdateConfigResp(other.getUpdateConfigResp());
                    break;
                }
                case RPC_RESP: {
                    mergeRpcResp(other.getRpcResp());
                    break;
                }
                case ACTION_RESP: {
                    mergeActionResp(other.getActionResp());
                    break;
                }
                case RESPTYPE_NOT_SET: {
                    break;
                }
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            org.broadband_forum.obbaa.onu.pm.message.gpb.message.Response parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (org.broadband_forum.obbaa.onu.pm.message.gpb.message.Response) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        public RespTypeCase
        getRespTypeCase() {
            return RespTypeCase.forNumber(
                    respTypeCase_);
        }

        public Builder clearRespType() {
            respTypeCase_ = 0;
            respType_ = null;
            onChanged();
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.HelloResp hello_resp = 3;</code>
         *
         * @return Whether the helloResp field is set.
         */
        public boolean hasHelloResp() {
            return respTypeCase_ == 3;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.HelloResp hello_resp = 3;</code>
         *
         * @return The helloResp.
         */
        public org.broadband_forum.obbaa.onu.pm.message.gpb.message.HelloResp getHelloResp() {
            if (helloRespBuilder_ == null) {
                if (respTypeCase_ == 3) {
                    return (org.broadband_forum.obbaa.onu.pm.message.gpb.message.HelloResp) respType_;
                }
                return org.broadband_forum.obbaa.onu.pm.message.gpb.message.HelloResp.getDefaultInstance();
            } else {
                if (respTypeCase_ == 3) {
                    return helloRespBuilder_.getMessage();
                }
                return org.broadband_forum.obbaa.onu.pm.message.gpb.message.HelloResp.getDefaultInstance();
            }
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.HelloResp hello_resp = 3;</code>
         */
        public Builder setHelloResp(org.broadband_forum.obbaa.onu.pm.message.gpb.message.HelloResp value) {
            if (helloRespBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                respType_ = value;
                onChanged();
            } else {
                helloRespBuilder_.setMessage(value);
            }
            respTypeCase_ = 3;
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.HelloResp hello_resp = 3;</code>
         */
        public Builder setHelloResp(
                org.broadband_forum.obbaa.onu.pm.message.gpb.message.HelloResp.Builder builderForValue) {
            if (helloRespBuilder_ == null) {
                respType_ = builderForValue.build();
                onChanged();
            } else {
                helloRespBuilder_.setMessage(builderForValue.build());
            }
            respTypeCase_ = 3;
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.HelloResp hello_resp = 3;</code>
         */
        public Builder mergeHelloResp(org.broadband_forum.obbaa.onu.pm.message.gpb.message.HelloResp value) {
            if (helloRespBuilder_ == null) {
                if (respTypeCase_ == 3 &&
                        respType_ != org.broadband_forum.obbaa.onu.pm.message.gpb.message.HelloResp.getDefaultInstance()) {
                    respType_ = org.broadband_forum.obbaa.onu.pm.message.gpb.message.HelloResp.newBuilder((org.broadband_forum.obbaa.onu.pm.message.gpb.message.HelloResp) respType_)
                            .mergeFrom(value).buildPartial();
                } else {
                    respType_ = value;
                }
                onChanged();
            } else {
                if (respTypeCase_ == 3) {
                    helloRespBuilder_.mergeFrom(value);
                }
                helloRespBuilder_.setMessage(value);
            }
            respTypeCase_ = 3;
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.HelloResp hello_resp = 3;</code>
         */
        public Builder clearHelloResp() {
            if (helloRespBuilder_ == null) {
                if (respTypeCase_ == 3) {
                    respTypeCase_ = 0;
                    respType_ = null;
                    onChanged();
                }
            } else {
                if (respTypeCase_ == 3) {
                    respTypeCase_ = 0;
                    respType_ = null;
                }
                helloRespBuilder_.clear();
            }
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.HelloResp hello_resp = 3;</code>
         */
        public org.broadband_forum.obbaa.onu.pm.message.gpb.message.HelloResp.Builder getHelloRespBuilder() {
            return getHelloRespFieldBuilder().getBuilder();
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.HelloResp hello_resp = 3;</code>
         */
        public org.broadband_forum.obbaa.onu.pm.message.gpb.message.HelloRespOrBuilder getHelloRespOrBuilder() {
            if ((respTypeCase_ == 3) && (helloRespBuilder_ != null)) {
                return helloRespBuilder_.getMessageOrBuilder();
            } else {
                if (respTypeCase_ == 3) {
                    return (org.broadband_forum.obbaa.onu.pm.message.gpb.message.HelloResp) respType_;
                }
                return org.broadband_forum.obbaa.onu.pm.message.gpb.message.HelloResp.getDefaultInstance();
            }
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.HelloResp hello_resp = 3;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                org.broadband_forum.obbaa.onu.pm.message.gpb.message.HelloResp, org.broadband_forum.obbaa.onu.pm.message.gpb.message.HelloResp.Builder, org.broadband_forum.obbaa.onu.pm.message.gpb.message.HelloRespOrBuilder>
        getHelloRespFieldBuilder() {
            if (helloRespBuilder_ == null) {
                if (!(respTypeCase_ == 3)) {
                    respType_ = org.broadband_forum.obbaa.onu.pm.message.gpb.message.HelloResp.getDefaultInstance();
                }
                helloRespBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        org.broadband_forum.obbaa.onu.pm.message.gpb.message.HelloResp, org.broadband_forum.obbaa.onu.pm.message.gpb.message.HelloResp.Builder, org.broadband_forum.obbaa.onu.pm.message.gpb.message.HelloRespOrBuilder>(
                        (org.broadband_forum.obbaa.onu.pm.message.gpb.message.HelloResp) respType_,
                        getParentForChildren(),
                        isClean());
                respType_ = null;
            }
            respTypeCase_ = 3;
            onChanged();
            return helloRespBuilder_;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.GetDataResp get_resp = 4;</code>
         *
         * @return Whether the getResp field is set.
         */
        public boolean hasGetResp() {
            return respTypeCase_ == 4;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.GetDataResp get_resp = 4;</code>
         *
         * @return The getResp.
         */
        public org.broadband_forum.obbaa.onu.pm.message.gpb.message.GetDataResp getGetResp() {
            if (getRespBuilder_ == null) {
                if (respTypeCase_ == 4) {
                    return (org.broadband_forum.obbaa.onu.pm.message.gpb.message.GetDataResp) respType_;
                }
                return org.broadband_forum.obbaa.onu.pm.message.gpb.message.GetDataResp.getDefaultInstance();
            } else {
                if (respTypeCase_ == 4) {
                    return getRespBuilder_.getMessage();
                }
                return org.broadband_forum.obbaa.onu.pm.message.gpb.message.GetDataResp.getDefaultInstance();
            }
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.GetDataResp get_resp = 4;</code>
         */
        public Builder setGetResp(org.broadband_forum.obbaa.onu.pm.message.gpb.message.GetDataResp value) {
            if (getRespBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                respType_ = value;
                onChanged();
            } else {
                getRespBuilder_.setMessage(value);
            }
            respTypeCase_ = 4;
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.GetDataResp get_resp = 4;</code>
         */
        public Builder setGetResp(
                org.broadband_forum.obbaa.onu.pm.message.gpb.message.GetDataResp.Builder builderForValue) {
            if (getRespBuilder_ == null) {
                respType_ = builderForValue.build();
                onChanged();
            } else {
                getRespBuilder_.setMessage(builderForValue.build());
            }
            respTypeCase_ = 4;
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.GetDataResp get_resp = 4;</code>
         */
        public Builder mergeGetResp(org.broadband_forum.obbaa.onu.pm.message.gpb.message.GetDataResp value) {
            if (getRespBuilder_ == null) {
                if (respTypeCase_ == 4 &&
                        respType_ != org.broadband_forum.obbaa.onu.pm.message.gpb.message.GetDataResp.getDefaultInstance()) {
                    respType_ = org.broadband_forum.obbaa.onu.pm.message.gpb.message.GetDataResp.newBuilder((org.broadband_forum.obbaa.onu.pm.message.gpb.message.GetDataResp) respType_)
                            .mergeFrom(value).buildPartial();
                } else {
                    respType_ = value;
                }
                onChanged();
            } else {
                if (respTypeCase_ == 4) {
                    getRespBuilder_.mergeFrom(value);
                }
                getRespBuilder_.setMessage(value);
            }
            respTypeCase_ = 4;
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.GetDataResp get_resp = 4;</code>
         */
        public Builder clearGetResp() {
            if (getRespBuilder_ == null) {
                if (respTypeCase_ == 4) {
                    respTypeCase_ = 0;
                    respType_ = null;
                    onChanged();
                }
            } else {
                if (respTypeCase_ == 4) {
                    respTypeCase_ = 0;
                    respType_ = null;
                }
                getRespBuilder_.clear();
            }
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.GetDataResp get_resp = 4;</code>
         */
        public org.broadband_forum.obbaa.onu.pm.message.gpb.message.GetDataResp.Builder getGetRespBuilder() {
            return getGetRespFieldBuilder().getBuilder();
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.GetDataResp get_resp = 4;</code>
         */
        public org.broadband_forum.obbaa.onu.pm.message.gpb.message.GetDataRespOrBuilder getGetRespOrBuilder() {
            if ((respTypeCase_ == 4) && (getRespBuilder_ != null)) {
                return getRespBuilder_.getMessageOrBuilder();
            } else {
                if (respTypeCase_ == 4) {
                    return (org.broadband_forum.obbaa.onu.pm.message.gpb.message.GetDataResp) respType_;
                }
                return org.broadband_forum.obbaa.onu.pm.message.gpb.message.GetDataResp.getDefaultInstance();
            }
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.GetDataResp get_resp = 4;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                org.broadband_forum.obbaa.onu.pm.message.gpb.message.GetDataResp, org.broadband_forum.obbaa.onu.pm.message.gpb.message.GetDataResp.Builder, org.broadband_forum.obbaa.onu.pm.message.gpb.message.GetDataRespOrBuilder>
        getGetRespFieldBuilder() {
            if (getRespBuilder_ == null) {
                if (!(respTypeCase_ == 4)) {
                    respType_ = org.broadband_forum.obbaa.onu.pm.message.gpb.message.GetDataResp.getDefaultInstance();
                }
                getRespBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        org.broadband_forum.obbaa.onu.pm.message.gpb.message.GetDataResp, org.broadband_forum.obbaa.onu.pm.message.gpb.message.GetDataResp.Builder, org.broadband_forum.obbaa.onu.pm.message.gpb.message.GetDataRespOrBuilder>(
                        (org.broadband_forum.obbaa.onu.pm.message.gpb.message.GetDataResp) respType_,
                        getParentForChildren(),
                        isClean());
                respType_ = null;
            }
            respTypeCase_ = 4;
            onChanged();
            return getRespBuilder_;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.ReplaceConfigResp replace_config_resp = 5;</code>
         *
         * @return Whether the replaceConfigResp field is set.
         */
        public boolean hasReplaceConfigResp() {
            return respTypeCase_ == 5;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.ReplaceConfigResp replace_config_resp = 5;</code>
         *
         * @return The replaceConfigResp.
         */
        public org.broadband_forum.obbaa.onu.pm.message.gpb.message.ReplaceConfigResp getReplaceConfigResp() {
            if (replaceConfigRespBuilder_ == null) {
                if (respTypeCase_ == 5) {
                    return (org.broadband_forum.obbaa.onu.pm.message.gpb.message.ReplaceConfigResp) respType_;
                }
                return org.broadband_forum.obbaa.onu.pm.message.gpb.message.ReplaceConfigResp.getDefaultInstance();
            } else {
                if (respTypeCase_ == 5) {
                    return replaceConfigRespBuilder_.getMessage();
                }
                return org.broadband_forum.obbaa.onu.pm.message.gpb.message.ReplaceConfigResp.getDefaultInstance();
            }
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.ReplaceConfigResp replace_config_resp = 5;</code>
         */
        public Builder setReplaceConfigResp(org.broadband_forum.obbaa.onu.pm.message.gpb.message.ReplaceConfigResp value) {
            if (replaceConfigRespBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                respType_ = value;
                onChanged();
            } else {
                replaceConfigRespBuilder_.setMessage(value);
            }
            respTypeCase_ = 5;
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.ReplaceConfigResp replace_config_resp = 5;</code>
         */
        public Builder setReplaceConfigResp(
                org.broadband_forum.obbaa.onu.pm.message.gpb.message.ReplaceConfigResp.Builder builderForValue) {
            if (replaceConfigRespBuilder_ == null) {
                respType_ = builderForValue.build();
                onChanged();
            } else {
                replaceConfigRespBuilder_.setMessage(builderForValue.build());
            }
            respTypeCase_ = 5;
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.ReplaceConfigResp replace_config_resp = 5;</code>
         */
        public Builder mergeReplaceConfigResp(org.broadband_forum.obbaa.onu.pm.message.gpb.message.ReplaceConfigResp value) {
            if (replaceConfigRespBuilder_ == null) {
                if (respTypeCase_ == 5 &&
                        respType_ != org.broadband_forum.obbaa.onu.pm.message.gpb.message.ReplaceConfigResp.getDefaultInstance()) {
                    respType_ = org.broadband_forum.obbaa.onu.pm.message.gpb.message.ReplaceConfigResp.newBuilder((org.broadband_forum.obbaa.onu.pm.message.gpb.message.ReplaceConfigResp) respType_)
                            .mergeFrom(value).buildPartial();
                } else {
                    respType_ = value;
                }
                onChanged();
            } else {
                if (respTypeCase_ == 5) {
                    replaceConfigRespBuilder_.mergeFrom(value);
                }
                replaceConfigRespBuilder_.setMessage(value);
            }
            respTypeCase_ = 5;
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.ReplaceConfigResp replace_config_resp = 5;</code>
         */
        public Builder clearReplaceConfigResp() {
            if (replaceConfigRespBuilder_ == null) {
                if (respTypeCase_ == 5) {
                    respTypeCase_ = 0;
                    respType_ = null;
                    onChanged();
                }
            } else {
                if (respTypeCase_ == 5) {
                    respTypeCase_ = 0;
                    respType_ = null;
                }
                replaceConfigRespBuilder_.clear();
            }
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.ReplaceConfigResp replace_config_resp = 5;</code>
         */
        public org.broadband_forum.obbaa.onu.pm.message.gpb.message.ReplaceConfigResp.Builder getReplaceConfigRespBuilder() {
            return getReplaceConfigRespFieldBuilder().getBuilder();
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.ReplaceConfigResp replace_config_resp = 5;</code>
         */
        public org.broadband_forum.obbaa.onu.pm.message.gpb.message.ReplaceConfigRespOrBuilder getReplaceConfigRespOrBuilder() {
            if ((respTypeCase_ == 5) && (replaceConfigRespBuilder_ != null)) {
                return replaceConfigRespBuilder_.getMessageOrBuilder();
            } else {
                if (respTypeCase_ == 5) {
                    return (org.broadband_forum.obbaa.onu.pm.message.gpb.message.ReplaceConfigResp) respType_;
                }
                return org.broadband_forum.obbaa.onu.pm.message.gpb.message.ReplaceConfigResp.getDefaultInstance();
            }
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.ReplaceConfigResp replace_config_resp = 5;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                org.broadband_forum.obbaa.onu.pm.message.gpb.message.ReplaceConfigResp, org.broadband_forum.obbaa.onu.pm.message.gpb.message.ReplaceConfigResp.Builder, org.broadband_forum.obbaa.onu.pm.message.gpb.message.ReplaceConfigRespOrBuilder>
        getReplaceConfigRespFieldBuilder() {
            if (replaceConfigRespBuilder_ == null) {
                if (!(respTypeCase_ == 5)) {
                    respType_ = org.broadband_forum.obbaa.onu.pm.message.gpb.message.ReplaceConfigResp.getDefaultInstance();
                }
                replaceConfigRespBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        org.broadband_forum.obbaa.onu.pm.message.gpb.message.ReplaceConfigResp, org.broadband_forum.obbaa.onu.pm.message.gpb.message.ReplaceConfigResp.Builder, org.broadband_forum.obbaa.onu.pm.message.gpb.message.ReplaceConfigRespOrBuilder>(
                        (org.broadband_forum.obbaa.onu.pm.message.gpb.message.ReplaceConfigResp) respType_,
                        getParentForChildren(),
                        isClean());
                respType_ = null;
            }
            respTypeCase_ = 5;
            onChanged();
            return replaceConfigRespBuilder_;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.UpdateConfigResp update_config_resp = 6;</code>
         *
         * @return Whether the updateConfigResp field is set.
         */
        public boolean hasUpdateConfigResp() {
            return respTypeCase_ == 6;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.UpdateConfigResp update_config_resp = 6;</code>
         *
         * @return The updateConfigResp.
         */
        public org.broadband_forum.obbaa.onu.pm.message.gpb.message.UpdateConfigResp getUpdateConfigResp() {
            if (updateConfigRespBuilder_ == null) {
                if (respTypeCase_ == 6) {
                    return (org.broadband_forum.obbaa.onu.pm.message.gpb.message.UpdateConfigResp) respType_;
                }
                return org.broadband_forum.obbaa.onu.pm.message.gpb.message.UpdateConfigResp.getDefaultInstance();
            } else {
                if (respTypeCase_ == 6) {
                    return updateConfigRespBuilder_.getMessage();
                }
                return org.broadband_forum.obbaa.onu.pm.message.gpb.message.UpdateConfigResp.getDefaultInstance();
            }
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.UpdateConfigResp update_config_resp = 6;</code>
         */
        public Builder setUpdateConfigResp(org.broadband_forum.obbaa.onu.pm.message.gpb.message.UpdateConfigResp value) {
            if (updateConfigRespBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                respType_ = value;
                onChanged();
            } else {
                updateConfigRespBuilder_.setMessage(value);
            }
            respTypeCase_ = 6;
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.UpdateConfigResp update_config_resp = 6;</code>
         */
        public Builder setUpdateConfigResp(
                org.broadband_forum.obbaa.onu.pm.message.gpb.message.UpdateConfigResp.Builder builderForValue) {
            if (updateConfigRespBuilder_ == null) {
                respType_ = builderForValue.build();
                onChanged();
            } else {
                updateConfigRespBuilder_.setMessage(builderForValue.build());
            }
            respTypeCase_ = 6;
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.UpdateConfigResp update_config_resp = 6;</code>
         */
        public Builder mergeUpdateConfigResp(org.broadband_forum.obbaa.onu.pm.message.gpb.message.UpdateConfigResp value) {
            if (updateConfigRespBuilder_ == null) {
                if (respTypeCase_ == 6 &&
                        respType_ != org.broadband_forum.obbaa.onu.pm.message.gpb.message.UpdateConfigResp.getDefaultInstance()) {
                    respType_ = org.broadband_forum.obbaa.onu.pm.message.gpb.message.UpdateConfigResp.newBuilder((org.broadband_forum.obbaa.onu.pm.message.gpb.message.UpdateConfigResp) respType_)
                            .mergeFrom(value).buildPartial();
                } else {
                    respType_ = value;
                }
                onChanged();
            } else {
                if (respTypeCase_ == 6) {
                    updateConfigRespBuilder_.mergeFrom(value);
                }
                updateConfigRespBuilder_.setMessage(value);
            }
            respTypeCase_ = 6;
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.UpdateConfigResp update_config_resp = 6;</code>
         */
        public Builder clearUpdateConfigResp() {
            if (updateConfigRespBuilder_ == null) {
                if (respTypeCase_ == 6) {
                    respTypeCase_ = 0;
                    respType_ = null;
                    onChanged();
                }
            } else {
                if (respTypeCase_ == 6) {
                    respTypeCase_ = 0;
                    respType_ = null;
                }
                updateConfigRespBuilder_.clear();
            }
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.UpdateConfigResp update_config_resp = 6;</code>
         */
        public org.broadband_forum.obbaa.onu.pm.message.gpb.message.UpdateConfigResp.Builder getUpdateConfigRespBuilder() {
            return getUpdateConfigRespFieldBuilder().getBuilder();
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.UpdateConfigResp update_config_resp = 6;</code>
         */
        public org.broadband_forum.obbaa.onu.pm.message.gpb.message.UpdateConfigRespOrBuilder getUpdateConfigRespOrBuilder() {
            if ((respTypeCase_ == 6) && (updateConfigRespBuilder_ != null)) {
                return updateConfigRespBuilder_.getMessageOrBuilder();
            } else {
                if (respTypeCase_ == 6) {
                    return (org.broadband_forum.obbaa.onu.pm.message.gpb.message.UpdateConfigResp) respType_;
                }
                return org.broadband_forum.obbaa.onu.pm.message.gpb.message.UpdateConfigResp.getDefaultInstance();
            }
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.UpdateConfigResp update_config_resp = 6;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                org.broadband_forum.obbaa.onu.pm.message.gpb.message.UpdateConfigResp, org.broadband_forum.obbaa.onu.pm.message.gpb.message.UpdateConfigResp.Builder, org.broadband_forum.obbaa.onu.pm.message.gpb.message.UpdateConfigRespOrBuilder>
        getUpdateConfigRespFieldBuilder() {
            if (updateConfigRespBuilder_ == null) {
                if (!(respTypeCase_ == 6)) {
                    respType_ = org.broadband_forum.obbaa.onu.pm.message.gpb.message.UpdateConfigResp.getDefaultInstance();
                }
                updateConfigRespBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        org.broadband_forum.obbaa.onu.pm.message.gpb.message.UpdateConfigResp, org.broadband_forum.obbaa.onu.pm.message.gpb.message.UpdateConfigResp.Builder, org.broadband_forum.obbaa.onu.pm.message.gpb.message.UpdateConfigRespOrBuilder>(
                        (org.broadband_forum.obbaa.onu.pm.message.gpb.message.UpdateConfigResp) respType_,
                        getParentForChildren(),
                        isClean());
                respType_ = null;
            }
            respTypeCase_ = 6;
            onChanged();
            return updateConfigRespBuilder_;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.RPCResp rpc_resp = 7;</code>
         *
         * @return Whether the rpcResp field is set.
         */
        public boolean hasRpcResp() {
            return respTypeCase_ == 7;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.RPCResp rpc_resp = 7;</code>
         *
         * @return The rpcResp.
         */
        public org.broadband_forum.obbaa.onu.pm.message.gpb.message.RPCResp getRpcResp() {
            if (rpcRespBuilder_ == null) {
                if (respTypeCase_ == 7) {
                    return (org.broadband_forum.obbaa.onu.pm.message.gpb.message.RPCResp) respType_;
                }
                return org.broadband_forum.obbaa.onu.pm.message.gpb.message.RPCResp.getDefaultInstance();
            } else {
                if (respTypeCase_ == 7) {
                    return rpcRespBuilder_.getMessage();
                }
                return org.broadband_forum.obbaa.onu.pm.message.gpb.message.RPCResp.getDefaultInstance();
            }
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.RPCResp rpc_resp = 7;</code>
         */
        public Builder setRpcResp(org.broadband_forum.obbaa.onu.pm.message.gpb.message.RPCResp value) {
            if (rpcRespBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                respType_ = value;
                onChanged();
            } else {
                rpcRespBuilder_.setMessage(value);
            }
            respTypeCase_ = 7;
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.RPCResp rpc_resp = 7;</code>
         */
        public Builder setRpcResp(
                org.broadband_forum.obbaa.onu.pm.message.gpb.message.RPCResp.Builder builderForValue) {
            if (rpcRespBuilder_ == null) {
                respType_ = builderForValue.build();
                onChanged();
            } else {
                rpcRespBuilder_.setMessage(builderForValue.build());
            }
            respTypeCase_ = 7;
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.RPCResp rpc_resp = 7;</code>
         */
        public Builder mergeRpcResp(org.broadband_forum.obbaa.onu.pm.message.gpb.message.RPCResp value) {
            if (rpcRespBuilder_ == null) {
                if (respTypeCase_ == 7 &&
                        respType_ != org.broadband_forum.obbaa.onu.pm.message.gpb.message.RPCResp.getDefaultInstance()) {
                    respType_ = org.broadband_forum.obbaa.onu.pm.message.gpb.message.RPCResp.newBuilder((org.broadband_forum.obbaa.onu.pm.message.gpb.message.RPCResp) respType_)
                            .mergeFrom(value).buildPartial();
                } else {
                    respType_ = value;
                }
                onChanged();
            } else {
                if (respTypeCase_ == 7) {
                    rpcRespBuilder_.mergeFrom(value);
                }
                rpcRespBuilder_.setMessage(value);
            }
            respTypeCase_ = 7;
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.RPCResp rpc_resp = 7;</code>
         */
        public Builder clearRpcResp() {
            if (rpcRespBuilder_ == null) {
                if (respTypeCase_ == 7) {
                    respTypeCase_ = 0;
                    respType_ = null;
                    onChanged();
                }
            } else {
                if (respTypeCase_ == 7) {
                    respTypeCase_ = 0;
                    respType_ = null;
                }
                rpcRespBuilder_.clear();
            }
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.RPCResp rpc_resp = 7;</code>
         */
        public org.broadband_forum.obbaa.onu.pm.message.gpb.message.RPCResp.Builder getRpcRespBuilder() {
            return getRpcRespFieldBuilder().getBuilder();
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.RPCResp rpc_resp = 7;</code>
         */
        public org.broadband_forum.obbaa.onu.pm.message.gpb.message.RPCRespOrBuilder getRpcRespOrBuilder() {
            if ((respTypeCase_ == 7) && (rpcRespBuilder_ != null)) {
                return rpcRespBuilder_.getMessageOrBuilder();
            } else {
                if (respTypeCase_ == 7) {
                    return (org.broadband_forum.obbaa.onu.pm.message.gpb.message.RPCResp) respType_;
                }
                return org.broadband_forum.obbaa.onu.pm.message.gpb.message.RPCResp.getDefaultInstance();
            }
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.RPCResp rpc_resp = 7;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                org.broadband_forum.obbaa.onu.pm.message.gpb.message.RPCResp, org.broadband_forum.obbaa.onu.pm.message.gpb.message.RPCResp.Builder, org.broadband_forum.obbaa.onu.pm.message.gpb.message.RPCRespOrBuilder>
        getRpcRespFieldBuilder() {
            if (rpcRespBuilder_ == null) {
                if (!(respTypeCase_ == 7)) {
                    respType_ = org.broadband_forum.obbaa.onu.pm.message.gpb.message.RPCResp.getDefaultInstance();
                }
                rpcRespBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        org.broadband_forum.obbaa.onu.pm.message.gpb.message.RPCResp, org.broadband_forum.obbaa.onu.pm.message.gpb.message.RPCResp.Builder, org.broadband_forum.obbaa.onu.pm.message.gpb.message.RPCRespOrBuilder>(
                        (org.broadband_forum.obbaa.onu.pm.message.gpb.message.RPCResp) respType_,
                        getParentForChildren(),
                        isClean());
                respType_ = null;
            }
            respTypeCase_ = 7;
            onChanged();
            return rpcRespBuilder_;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.ActionResp action_resp = 8;</code>
         *
         * @return Whether the actionResp field is set.
         */
        public boolean hasActionResp() {
            return respTypeCase_ == 8;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.ActionResp action_resp = 8;</code>
         *
         * @return The actionResp.
         */
        public org.broadband_forum.obbaa.onu.pm.message.gpb.message.ActionResp getActionResp() {
            if (actionRespBuilder_ == null) {
                if (respTypeCase_ == 8) {
                    return (org.broadband_forum.obbaa.onu.pm.message.gpb.message.ActionResp) respType_;
                }
                return org.broadband_forum.obbaa.onu.pm.message.gpb.message.ActionResp.getDefaultInstance();
            } else {
                if (respTypeCase_ == 8) {
                    return actionRespBuilder_.getMessage();
                }
                return org.broadband_forum.obbaa.onu.pm.message.gpb.message.ActionResp.getDefaultInstance();
            }
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.ActionResp action_resp = 8;</code>
         */
        public Builder setActionResp(org.broadband_forum.obbaa.onu.pm.message.gpb.message.ActionResp value) {
            if (actionRespBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                respType_ = value;
                onChanged();
            } else {
                actionRespBuilder_.setMessage(value);
            }
            respTypeCase_ = 8;
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.ActionResp action_resp = 8;</code>
         */
        public Builder setActionResp(
                org.broadband_forum.obbaa.onu.pm.message.gpb.message.ActionResp.Builder builderForValue) {
            if (actionRespBuilder_ == null) {
                respType_ = builderForValue.build();
                onChanged();
            } else {
                actionRespBuilder_.setMessage(builderForValue.build());
            }
            respTypeCase_ = 8;
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.ActionResp action_resp = 8;</code>
         */
        public Builder mergeActionResp(org.broadband_forum.obbaa.onu.pm.message.gpb.message.ActionResp value) {
            if (actionRespBuilder_ == null) {
                if (respTypeCase_ == 8 &&
                        respType_ != org.broadband_forum.obbaa.onu.pm.message.gpb.message.ActionResp.getDefaultInstance()) {
                    respType_ = org.broadband_forum.obbaa.onu.pm.message.gpb.message.ActionResp.newBuilder((org.broadband_forum.obbaa.onu.pm.message.gpb.message.ActionResp) respType_)
                            .mergeFrom(value).buildPartial();
                } else {
                    respType_ = value;
                }
                onChanged();
            } else {
                if (respTypeCase_ == 8) {
                    actionRespBuilder_.mergeFrom(value);
                }
                actionRespBuilder_.setMessage(value);
            }
            respTypeCase_ = 8;
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.ActionResp action_resp = 8;</code>
         */
        public Builder clearActionResp() {
            if (actionRespBuilder_ == null) {
                if (respTypeCase_ == 8) {
                    respTypeCase_ = 0;
                    respType_ = null;
                    onChanged();
                }
            } else {
                if (respTypeCase_ == 8) {
                    respTypeCase_ = 0;
                    respType_ = null;
                }
                actionRespBuilder_.clear();
            }
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.ActionResp action_resp = 8;</code>
         */
        public org.broadband_forum.obbaa.onu.pm.message.gpb.message.ActionResp.Builder getActionRespBuilder() {
            return getActionRespFieldBuilder().getBuilder();
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.ActionResp action_resp = 8;</code>
         */
        public org.broadband_forum.obbaa.onu.pm.message.gpb.message.ActionRespOrBuilder getActionRespOrBuilder() {
            if ((respTypeCase_ == 8) && (actionRespBuilder_ != null)) {
                return actionRespBuilder_.getMessageOrBuilder();
            } else {
                if (respTypeCase_ == 8) {
                    return (org.broadband_forum.obbaa.onu.pm.message.gpb.message.ActionResp) respType_;
                }
                return org.broadband_forum.obbaa.onu.pm.message.gpb.message.ActionResp.getDefaultInstance();
            }
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.ActionResp action_resp = 8;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                org.broadband_forum.obbaa.onu.pm.message.gpb.message.ActionResp, org.broadband_forum.obbaa.onu.pm.message.gpb.message.ActionResp.Builder, org.broadband_forum.obbaa.onu.pm.message.gpb.message.ActionRespOrBuilder>
        getActionRespFieldBuilder() {
            if (actionRespBuilder_ == null) {
                if (!(respTypeCase_ == 8)) {
                    respType_ = org.broadband_forum.obbaa.onu.pm.message.gpb.message.ActionResp.getDefaultInstance();
                }
                actionRespBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        org.broadband_forum.obbaa.onu.pm.message.gpb.message.ActionResp, org.broadband_forum.obbaa.onu.pm.message.gpb.message.ActionResp.Builder, org.broadband_forum.obbaa.onu.pm.message.gpb.message.ActionRespOrBuilder>(
                        (org.broadband_forum.obbaa.onu.pm.message.gpb.message.ActionResp) respType_,
                        getParentForChildren(),
                        isClean());
                respType_ = null;
            }
            respTypeCase_ = 8;
            onChanged();
            return actionRespBuilder_;
        }

        @java.lang.Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:tr451_vomci_nbi_message.v1.Response)
    }

}

