// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tr451_vomci_nbi_message.proto

package org.broadband_forum.obbaa.onu.pm.message.gpb.message;

public interface UpdateConfigOrBuilder extends
        // @@protoc_insertion_point(interface_extends:tr451_vomci_nbi_message.v1.UpdateConfig)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.tr451_vomci_nbi_message.v1.UpdateConfigInstance update_config_inst = 1;</code>
     *
     * @return Whether the updateConfigInst field is set.
     */
    boolean hasUpdateConfigInst();

    /**
     * <code>.tr451_vomci_nbi_message.v1.UpdateConfigInstance update_config_inst = 1;</code>
     *
     * @return The updateConfigInst.
     */
    org.broadband_forum.obbaa.onu.pm.message.gpb.message.UpdateConfigInstance getUpdateConfigInst();

    /**
     * <code>.tr451_vomci_nbi_message.v1.UpdateConfigInstance update_config_inst = 1;</code>
     */
    org.broadband_forum.obbaa.onu.pm.message.gpb.message.UpdateConfigInstanceOrBuilder getUpdateConfigInstOrBuilder();

    /**
     * <code>.tr451_vomci_nbi_message.v1.UpdateConfigReplica update_config_replica = 2;</code>
     *
     * @return Whether the updateConfigReplica field is set.
     */
    boolean hasUpdateConfigReplica();

    /**
     * <code>.tr451_vomci_nbi_message.v1.UpdateConfigReplica update_config_replica = 2;</code>
     *
     * @return The updateConfigReplica.
     */
    org.broadband_forum.obbaa.onu.pm.message.gpb.message.UpdateConfigReplica getUpdateConfigReplica();

    /**
     * <code>.tr451_vomci_nbi_message.v1.UpdateConfigReplica update_config_replica = 2;</code>
     */
    org.broadband_forum.obbaa.onu.pm.message.gpb.message.UpdateConfigReplicaOrBuilder getUpdateConfigReplicaOrBuilder();

    /**
     * <pre>
     * Optional: Datastore tag used to
     * </pre>
     *
     * <code>string datastore_tag = 3;</code>
     *
     * @return The datastoreTag.
     */
    java.lang.String getDatastoreTag();

    /**
     * <pre>
     * Optional: Datastore tag used to
     * </pre>
     *
     * <code>string datastore_tag = 3;</code>
     *
     * @return The bytes for datastoreTag.
     */
    com.google.protobuf.ByteString
    getDatastoreTagBytes();

    org.broadband_forum.obbaa.onu.pm.message.gpb.message.UpdateConfig.ReqTypeCase getReqTypeCase();
}
